### ISSUE TITLE
Update sessions range on dashboard

### ISSUE THREAD

**Issue by scottqueen-bixal** [18F/analytics.usa.gov#1104]
## Background

Because of the inconsistency we are having with hourly metrics for both `today` and `last-48-hours` reporting, (see, https://github.com/orgs/18F/projects/55/views/1?filterQuery=assignee%3A%22scottqueen-bixal%22&pane=issue&itemId=50003426) we are going to move over to a 30day session based reporting as a replacement.

See this conversation thread for more detail -> https://gsa-tts.slack.com/archives/C05S1B327MH/p1705421899626399

## User Story
As a user visiting https://analytics.usa.gov/, I should see a bar chart displaying "Daily Sessions in the Past 30 Days" by day
As a user visiting https://analytics.usa.gov/, I should see a SUM of the total number for the sessions in the past 30 days 

## Acceptance Criteria

- [x]  id = `total_visitors` displays a SUM of the total number for the sessions in the past 90 days
- [x]  id = `total_visitors` displays `There were <sum> billion sessions over the past 90 days.`
- [x] chart with id = `time_series` is a bar chart displaying "Daily Sessions in the Past 30 Days" by day
- [x] chart with id = `time_series` displays `dd/mm` as notation along the X axis
- [x] chart with id = `time_series` displays a title for "Daily Sessions in the Past 30 Days"
- [x] chart with id = `time_series` does not display `Easter Time`

**Comment by scottqueen-bixal** [comment]
@nick-mon1 I've updated our reports to include `sessions-over-30-days.json` https://analytics-develop.app.cloud.gov/data/live/sessions-over-30-days.json

**Comment by nick-mon1** [comment]
@smarina04 Copy updates are ready for review https://github.com/18F/analytics.usa.gov/pull/1103

**Comment by scottqueen-bixal** [comment]
@nick-mon1 linking this slack comment as it is a decision point for moving forward with this update https://gsa-tts.slack.com/archives/C05S1B327MH/p1705595825206679?thread_ts=1705595482.488289&cid=C05S1B327MH
