### ISSUE TITLE
Upgrade Out-of-date Version (AngularJS) & Out-of-date Version (Bootstrap) for analytics.usa.gov

### ISSUE THREAD

**Issue by smarina04** [18F/analytics.usa.gov#1105]
Review report for:

- [x] Out of date version (angular.js)
- [x] Out of date version (bootstrap)
- [ ] review with scan team

These are flagged when the `_ga` query parameter is set as a cookie.

@XavierMetichecchia or @scottqueen-bixal, these out of date versions might be set via Google Analytics.
Any way on the server to change this?

Jekyll set's the client path in **config.yml**:

```
# Default data url (also needs to be in nginx.conf for cloud.gov deployment)
data_url: https://analytics.usa.gov/data

```

**Comment by XavierMetichecchia** [comment]
@smarina04 @sfrederick-gsa-gov Scott, Nick, and I met and took at look at the two mediums in the Invicti this scan. We think it may be some type of false positive. First of all those URLs don't exist, browsing to them just shows and access denied page. Second, its interpreting a cookie incorrectly as some sort of angular vulnerability in bootstrap. Nick confirmed there isn't any angular or bootstrap on the site at all. So humbly request the scan teams ruled it as a false positive if they are in agreement with us. If not, we would love further direction or explanation to resolve the issue.
