### ISSUE TITLE
*All* top domains over 7 days

### ISSUE THREAD

**Issue by konklone** [18F/analytics.usa.gov#111]
The new filtered profile should have 7 days' worth of data pretty soon. We can then export a pretty nice list of every domain that appears in it. It's well below 10,000, which is the maximum set size. And many have 0 visits, for some reason, so you could filter them to `visits>0` and cut it down further.

Since this is a great research dataset, it should be available in CSV and JSON. We can include it in the data listing, even if it's not turned into some epic graph.

There are staging domains and stuff in here, but any of those sites could just refrain from doing DAP reporting from non-final domains.

**Comment by cew821** [comment]
Let's tee this up for discussion next time we get the DAP team in the room. I think this would be a great thing to include in a big release after the first one.

**Comment by konklone** [comment]
Totally agree that it needs discussion with the DAP team - and, looking at the data, it'll need a bit more effort than the other reports if we want it to feel cleaner (like removing IP addresses). I'm going to send some samples to the DAP team, as I'm not sure the new profile is doing as much whitelisting as they're hoping for.

Still, I want to make sure we get some sort of substantive data release out soon. The data we've got so far is great and people are going to love it, but it also isn't deep enough for anyone to do any interesting research on. We'll get some very different wins out of a larger dataset than we will the live snapshots, and this one seems to me like the highest ROI of that nature.

**Comment by tdlowden** [comment]
+1 to discussion above. I had created a report that eliminates much of the staging clutter, but if you guys want to do a wholesale dump, we can do that.

**Comment by cew821** [comment]
How important is the whitelisting? Is it really a problem to have staging sites on the list?

**Comment by tdlowden** [comment]
Not too much of a worry, but there are more than you'd expect. I'm not against doing a full download.

**Comment by konklone** [comment]
This is done (at the 30 day level) and available for download.
