### ISSUE TITLE
Fix language report codes to display language name

### ISSUE THREAD

**Issue by nick-mon1** [18F/analytics.usa.gov#1127]
AC:  return both `language` and l`anguageCode` organized by values and total for s3 only, API will continue to report on `languageCode`

**Comment by scottqueen-bixal** [comment]
https://analytics.usa.gov/data/live/language.json if you look at live site you can see that the report returns language codes.
The GA4 mapping stated that `ga:language` and `language` were the same values, but in GA4 language returns the language display name.

When I was auditing the Query we made an update to those reports to return the `languageCode`, this keeps the values consistent across the api to what we return on v1

We probably want to keep the API values consistent, but may have options on reports written to s3: if consistency is flexible there.

Options:

1. return both `language` and `languageCode` organized by values and total for s3 only 
> easiest fix while still providing some consistency across data points
3. return just `language` for s3 and just `languageCode` for API
> most difference between reports and data on endpoint
5. return `languageCode` for both and handle display name with JS on front end 
> most consistent

**Comment by scottqueen-bixal** [comment]
@smarina04 if there is no preference #1 is the options @nick-mon1 and I like best

**Comment by smarina04** [comment]
Let’s go with the option 1
