### ISSUE TITLE
Finalize cache times before launch

### ISSUE THREAD

**Issue by konklone** [18F/analytics.usa.gov#113]
Right now, everything is cached at 0 seconds during the development and pre-launch process. Before launch, we'll want to adjust cache times to something that saves users time and us money. (From then on, gsa.github.io will be the only place we can try things out right away.)

Suggested cache times (which also require updates to code and instructions):

- [x] The dap.js snippet should routinely be given a cache time of 60 minutes.
- [x] The website should routinely be given a cache time of 5 minutes.
- [ ] The daily data should automatically be given a cache time of 5 minutes.

We could lengthen the cache time for the website when development becomes less rapid. And we can _always_ do CloudFront "invalidations" from the console to trigger changes to appear over a ~5-10 minute window, even if we set longer cache times.

However, I'm anticipating that we will want to make frequent production updates in the short-term post-launch window, and that we would be frustrated by having to wait more than 5 minutes for those changes to appear. 

The daily data's cache time is set to 5 minutes because when we do update it, we want it to take effect very soon. Frustrating, but I don't see that changing at any point with our current data strategy.

cc @cew821 @rypan @shawnbot @ramirezg

**Comment by gbinal** [comment]
@konklone - it seems like this was either completed or we're not on track to do it anytime soon.  I'm going to go ahead and close for now, but holler if that's a problem.
