### ISSUE TITLE
Update the verbiage based on GA4 frequency of updates

### ISSUE THREAD

**Issue by smarina04** [18F/analytics.usa.gov#1159]

**Comment by smarina04** [comment]
https://analytics-develop.app.cloud.gov/data/



![Image](https://github.com/18F/analytics.usa.gov/assets/3287495/d98e2da4-9d19-48fa-894e-0b2bcbd8cde4)

**Comment by levinmr** [comment]
Updated to read "Every 30 minutes" for realtime reports.  GA4's reporting docs list out 30 minutes as the frequency of updates to the realtime reporting API

https://developers.google.com/analytics/devguides/reporting/data/v1/rest/v1beta/properties/runRealtimeReport
