### ISSUE TITLE
Getting this data listed on Data.gov

### ISSUE THREAD

**Issue by cew821** [18F/analytics.usa.gov#117]
Should we describe our .json endpoints in the Project Open Data schema and publish them in our subdomain? Or should we just add entries describing them to GSA's public data catalog?

**Comment by konklone** [comment]
I think the latter - gsa.gov/data.json should include a reference to the data we're publishing here.

I kicked off an email thread internally last week about this, between DAP and GSA's open data liaison. Probably better to track that separately.

**Comment by cew821** [comment]
Sounds good.

**Comment by konklone** [comment]
cc-ing @rebeccawilliams @tdlowden - I've re-titled this task to track completion of this dataset appearing in http://gsa.gov/data.json.

That said, I'd have assumed the Digital Analytics Program's dataset would already be present in GSA's public data listing, or at least the enterprise inventory?

**Comment by rebeccawilliams** [comment]
GSA's redacted EDI needs work, but it doesn't look like it: https://catalog.data.gov/dataset/gsa-redacted-enterprise-data-inventory 

cc @philipashlock @jlberryhill

It would have been nice to see this happen with the launch! @rypan

**Comment by konklone** [comment]
This conversation has been kicked up once again internally, this time with @smarina04.

**Comment by nsinai** [comment]
Is there a launch checklist internal to GSA and/or 18F?

Executive Order 13642 (https://www.whitehouse.gov/the-press-office/2013/05/09/executive-order-making-open-and-machine-readable-new-default-government-) states that "the default state of new and modernized Government information resources shall be open and machine readable."  

This would seem to mean that GSA (including 18F) should consider data openness and machine-readability when starting/launching a new application or service. In practice, that should also include how the metadata about the data created/collected from a new application or service is cataloged in GSA's enterprise-wide data inventory.

**Comment by konklone** [comment]
This was worked on and discussed months before our public launch, but it wasn't done in time for launch and was not a blocker for launch.

> Is there a launch checklist internal to GSA and/or 18F?

18F isn't a program office, and can't create or manage inventory metadata on behalf of program teams.

**Comment by smarina04** [comment]
DAP team is working on getting the metadata published on data.gov.

**Comment by gbinal** [comment]
FYI - this is now in www.gsa.gov/data.json

**Comment by konklone** [comment]
It's...a little weird, though. There's a dataset called `"Analytics.USA.gov Datasets"` which has no URL at all, and then each main JSON file as a separate dataset that links directly to the JSON file. I don't think these are linked together in any sort of parent-child relationship, and I'm not sure how valuable the first dataset is without a URL field attached (like the `/data/` page we're almost done with).

**Comment by gbinal** [comment]
Yeah, we saw that, too, and totally agree.  We've [made a note](https://github.com/18F/data-inventory/issues/28) about it as part of our data inventory efforts and are following up with the GSA data inventory folks to correct it.
