### ISSUE TITLE
Add data definitions page to site

### ISSUE THREAD

**Issue by levinmr** [18F/analytics.usa.gov#1176]
As a user of the analytics site, I want a page which has a glossary of analytics terms (session, pageview, bounce rate, etc), so that I can understand the data presented.

Acceptance Criteria:
When a user is viewing the analytics.usa.gov site
Then a link appears in the header for "Glossary"

When a user clicks the link for the glossary
Then the user is navigated to the glossary page
And the standard header bar appears with navigation links to the other site pages

When a user is viewing the glossary page
Then the following content appears:

**Comment by MaroyaF** [comment]
@smarina04 This draft is ready for your review https://docs.google.com/document/d/1eedWoVwwfuya-P3nPR3JwHRRlmUiQS8heY7BAaoRrk4/edit#heading=h.m7xfhd3a7lms

**Comment by MaroyaF** [comment]
Closing this issue since there's another one (issue #1222). I'll add the link to the doc to the other issue.
