### ISSUE TITLE
Add engagement metrics to analytics.usa.gov

### ISSUE THREAD

**Issue by smarina04** [18F/analytics.usa.gov#1207]
Add the following two new metrics: 

userEngagementDuration
engagementRate

![Image](https://github.com/18F/analytics.usa.gov/assets/3287495/b3a5dea6-d396-4caa-8d15-89d65a829bbb)

**Comment by levinmr** [comment]
Sample reports for user engagement duration follow.  Calculating the duration divided by the total sessions gave: 

- 62.5 seconds engaged on average for the last 30 days
- 58.95 seconds engaged on average for the last 90 days

Raw data:

[engagement-duration-30-days.json](https://github.com/18F/analytics.usa.gov/files/14656594/engagement-duration-30-days.json)

[engagement-duration-90-days.json](https://github.com/18F/analytics.usa.gov/files/14656595/engagement-duration-90-days.json)

**Comment by MaroyaF** [comment]
@levinmr looks good, my only suggestion is to spell out average instead of Avg.

**Comment by smarina04** [comment]
@levinmr Agree with @MaroyaF - let's spell out Average. 

Also, in the raw data json files (all of them) - the description field is wrong.. it says ""description": "Top 20 sources that initiated a session for the last 30 days, measured by visits, for all sites." for all of the files - just letting you know so they can be corrected with a proper definition for all of them. This must have been copied from the top pages json.

**Comment by levinmr** [comment]
@smarina04 do you want these engagement reports to be listed on the data download page as well?

**Comment by levinmr** [comment]
I took a minute to try out adding a description below the engagement metric display.  I don't care for how it looks though.

![Image](https://github.com/18F/analytics.usa.gov/assets/3766065/151c53fe-5a76-4f32-a8f9-dc5d375f5471)

**Comment by smarina04** [comment]
@levinmr yeah, not a fan. get rid of the description. we will have to just explain it separately on the definitions page that is to be created.

**Comment by levinmr** [comment]
Per standup today, remove the "(Percent of Engaged Sessions)" from the header for engagement rate.

**Comment by levinmr** [comment]
Analytics-reporter changes to add engagement metrics report has been deployed to production in preparation for the corresponding website changes to be merged.  The engagement metric reports will need some time to populate before the values will appear on the site.
