### ISSUE TITLE
Update sentence under total users to reflect agency selected

### ISSUE THREAD

**Issue by MaroyaF** [18F/analytics.usa.gov#1208]
The statement stays the same even if the selection is not government-wide, which is misleading since it says "people on government websites".  It would be great if the statement could be updated based on the filter selection. 

For example, if I select "Department of Defense" then the statement would say " people on the Department of Defense websites and applications in the last 30 minutes".

We should also consider to add more context to the government-wide statement. I suggest to update it to " people on ** all federal** government websites or applications in the last 30 minutes"

![Image](https://github.com/18F/analytics.usa.gov/assets/161525037/3b858958-ac09-4e7f-acdb-aaffa80fd6e3)

**Comment by levinmr** [comment]
@MaroyaF the fix for this ticket is currently on develop.  https://analytics-develop.app.cloud.gov/

**Comment by MaroyaF** [comment]
@levinmr This is AWESOME and looks great!! Thank you so much for implementing this. Tagging @smarina04 so she's aware of the update and incase she wants to review.

**Comment by smarina04** [comment]
Love it, thanks @MaroyaF and @levinmr. Good to move forward.
