### ISSUE TITLE
Make header menu options lined up when screen is full size

### ISSUE THREAD

**Issue by MaroyaF** [18F/analytics.usa.gov#1211]
The header menu looks fine when the screen is collapsed (first pic) but it doesn't line up when the screen is full size (2nd screen shot). 

![Image](https://github.com/18F/analytics.usa.gov/assets/161525037/ece18048-3a9a-4ee4-9c9f-09ff067a70eb)

**Comment by MaroyaF** [comment]
I just also noticed that on mobile it says "About" and on desktop it says "About this site".

**Comment by levinmr** [comment]
@MaroyaF The changes to make the nav links always lined up in a row are on dev and staging.  The "About this site" changes to just "About" at somewhere between tablet and desktop sized browser.  I think it's intended to save space on the smaller screens.

**Comment by MaroyaF** [comment]
@levinmr This looks so much better, thank you so much! @smarina04 please review and let @levinmr know if you approve if these changes. Thanks
