### ISSUE TITLE
Add instructions content above filter dropdowns

### ISSUE THREAD

**Issue by MaroyaF** [18F/analytics.usa.gov#1213]
A title is needed for the filter dropdowns in the homepage and the data page for accessibility. A screen reader user wouldn't know there's a filter there as they are navigating the site.  I would also recommend moving the homepage filter below the header menu.

Below is a screenshot of the request and another screenshot of any example on the performance.gov site. 

![Image](https://github.com/18F/analytics.usa.gov/assets/161525037/e71c778c-e087-4f9f-850d-38fccfc71bb8)

![Image](https://github.com/18F/analytics.usa.gov/assets/161525037/08b2382f-a719-4365-a566-4ed78f31e7f2)

**Comment by levinmr** [comment]
Re:  screen readers.  There are properties on this select element for screen readers 

```
aria-label="Select an agency to display results"
id="analytics-agency-select"
title="Agency Selection Dropdown"
```
