### ISSUE TITLE
Add glossary page to analytics site

### ISSUE THREAD

**Issue by levinmr** [18F/analytics.usa.gov#1222]
Add a page for data definitions and/or glossary of analytics terms

Add links from:
- Engagement rate header to the glossary page
- Add links to glossary from site header
- Add link to the glossary page from the data page under Download the Data.  Text: "See data fields and metrics descriptions"

**Comment by MaroyaF** [comment]
@levinmr here's the link to the drafted page https://docs.google.com/document/d/1eedWoVwwfuya-P3nPR3JwHRRlmUiQS8heY7BAaoRrk4/edit#heading=h.m7xfhd3a7lms

**Comment by levinmr** [comment]
@MaroyaF @smarina04 My first pass at this feature is currently in the dev environment

**Comment by MaroyaF** [comment]
@levinmr I took a quick look, I'll review more in detail tomorrow. I have two edits;

1. There's two "Host Name", the second one should be "File Name"

![Image](https://github.com/18F/analytics.usa.gov/assets/161525037/b3150941-3432-4e31-adf9-ff91ed97e8a5)

2. Change this title to "Percent of engaged sessions" 

![Image](https://github.com/18F/analytics.usa.gov/assets/161525037/7a9d5fb2-aa88-4ac6-bb8e-40f8f8e8b34d)

**Comment by MaroyaF** [comment]
@levinmr Also, the "User Device Demographics" is missing from the description of data available on the site section.

**Comment by levinmr** [comment]
Made edits to the glossary/definitions headers, and also removed the FAQs section per Marina.  Fixed some missed items that Maroya pointed out as well.

There was consensus at standup yesterday that the content was not readable and the styling needed to be adjusted.  I changed the font slightly for the body copy and increased the line height a bit.  I also slightly indented subsections to indicate hierarchy.  I think it's easier to read now.  

See what you think @smarina04 @MaroyaF

**Comment by levinmr** [comment]
The dev site with the updated glossary is up now.  I believe that I addressed all feedback, and all links should work now.  Also included is the addition of the analytics icon image to the site header

**Comment by MaroyaF** [comment]
@levinmr Looks great! The only change I found is that file name and link url have the same definitions. The definition for link url should be "The full URL for a file download at the time of download."

**Comment by MaroyaF** [comment]
@levinmr Also, I suggest making the d in definitions to be lower case to be consistent with the other headings. 
![image](https://github.com/18F/analytics.usa.gov/assets/161525037/b0710088-01fa-4638-9703-c461021e989e)

**Comment by levinmr** [comment]
Headers for engagement metrics should link to their corresponding report description in the definitions page:
- Average Engagement Time Per Session 
- Percent of Engaged Sessions

**Comment by levinmr** [comment]
I have added the links with anchors as requested above.  I also added some logic which will automatically expand the accordion section if a link is clicked that navigates to that section.  This will be live in the dev in a minute or two.

**Comment by MaroyaF** [comment]
@levinmr the links go to the right sections but it didn't open the accordion for me

**Comment by levinmr** [comment]
> [@levinmr](https://github.com/levinmr) the links go to the right sections but it didn't open the accordion for me

This should be fixed now in the dev environment.  I tested it there and it's working for me.

**Comment by MaroyaF** [comment]
@levinmr looks great, the accordion expanded for both links!
