### ISSUE TITLE
Enable download into CSV

### ISSUE THREAD

**Issue by nsinai** [18F/analytics.usa.gov#131]
Awesome that folks can download stuff in JSON, but what about non-technical users who might want the numbers in CSV?

**Comment by gbinal** [comment]
Definitely agree that it's a worthwhile feature and one that we want to add.  Didn't include it in the initial MVP, though.  

One interim step could be to point to @konklone's [JSON-to-CSV converter](http://konklone.io/json/) in the documentation.

**Comment by konklone** [comment]
So @ramirezg and I actually already did most of the work for this over at https://github.com/18F/analytics-reporter/pull/49, expecting it would make it in for launch. We have a bit more time than we thought, so I'll attempt to get this in.

Bear in mind, @nsinai, not all of the reports make intuitive sense as a CSV, like the real-time number of people on federal .gov sites. I'd say the ones that make sense are:

* Visits per hour over the current day, where each row is an hour.
* Top 20 pages people are on right now, where each row is a page.
* Top 20 domains people are on over the last X days, where each row is a domain.

There's an argument for OS and browser numbers, but the current implementation means these would take more work, and so I'd prefer to get to them when we revisit the data output altogether (and start generating archival snapshots, etc).

**Comment by nsinai** [comment]
Great to hear @konklone  and @ramirezg.  Totally get this in the MVP, and some formats may be added in future versions.

I'm not sure I completely understand the assertion, @konklone, that real-time data isn't useful in a CSV export.  Wouldn't it essentially be a snapshot of how many people were on various .gov sites at the time that I downloaded that file?  I'm not sure the exact use case, but what about in research and academia?  I guess your point is it would make far more sense to build simple software to call the API every 5 minutes rather than manually download the file every 5 minutes....

In any case, very nice work!

**Comment by gbinal** [comment]
> I'm not sure I completely understand the assertion, @konklone, that real-time data isn't useful in a CSV export. 

@nsinai - right now, I think it's a single number, not broken out by sites.  Future versions that break that up would def. warrant csv versions.

**Comment by konklone** [comment]
Correct. I was ruling out the one big number, but included the "Top 20 pages people are on right now" in my list of data that would make sense as CSV.

**Comment by nsinai** [comment]
Awesome.  Keep calm and carry on.

**Comment by greggersh** [comment]
Just want to add a +1 to this; I shared the website on Facebook and got questions from non-technical friends about how to download data as a spreadsheet (CSV would suffice).

**Comment by nsinai** [comment]
Hi team -- any update on adding a CSV download feature?  It would make it easier for policy students to download, analyze, and use.

**Comment by konklone** [comment]
Given our discussions here and internally, I think this is very likely as a near-term line item, and is why we built a `--csv` option into [`analytics-reporter`](https://github.com/18F/analytics-reporter). I'd personally like to resolve and close this issue soon.

**Comment by nsinai** [comment]
Thanks @konklone

**Comment by tdlowden** [comment]
Various csv options now available. Closing.
