### ISSUE TITLE
Explain switch between individual pages and domains

### ISSUE THREAD

**Issue by nsinai** [18F/analytics.usa.gov#132]
Users can see top individual pages in real-time, but can only see top domains over time periods.  The switch from individual pages to domains is akin to changing the scale on an axis when presenting multiple graphs -- misleading unless you are hyper alert for it.

Are there important technical or user need reasons this was done? 

Should you note this change for the user?

**Comment by tdlowden** [comment]
Addressed by adding:

`People on a single, specific page now. We only count pages with at least 10 people on the page. Download the full dataset.`

&

`Visits over the last month to domains, including traffic to all pages within that domain. We only count pages with at least 1,000 visits in the last month. Download the full dataset.`
