### ISSUE TITLE
Document how other agencies can host

### ISSUE THREAD

**Issue by gbinal** [18F/analytics.usa.gov#133]
Hoping that agencies want to host a variant of this on their site, pulling in their analytics, we should have instructions on how they can do that.

**Comment by philipashlock** [comment]
:+1:

It would also be great if once they have those live, they could register them on analytics.usa.gov so that the site can act as a directory for more detailed analytics from each agency

**Comment by gbinal** [comment]
Totally agree.

**Comment by konklone** [comment]
Another option is to allow the main dashboard to be filtered intelligently to an agency's set of domains, e.g. `https://analytics.usa.gov/?agency=gsa` or `https://analytics.usa.gov/#gsa`. Each agency's set of domains could most easily be managed in DAP as a profile.

**Comment by philipashlock** [comment]
Yeah, I suspect you already have the capability to do that now with the access you have to the DAP account. Using the existing DAP accounts seems like the simplest and most straightforward way to expand to agency detail. I'm guessing agencies would still need to opt into that though. 

The ability to link to separately hosted instances of this would be valuable if agencies have expanded features or detail that's not available from the DAP account, eg perhaps agency specific conversion goals. I think there may also be opportunities for increased precision on agency specific accounts.

**Comment by konklone** [comment]
> The ability to link to separately hosted instances of this would be valuable if agencies have expanded features or detail that's not available from the DAP account, eg perhaps agency specific conversion goals. 

:+1:

> I think there may also be opportunities for increased precision on agency specific accounts.

You probably meant this more broadly, but FWIW we're disabling sampling on our API calls.

**Comment by gbinal** [comment]
The current documentation for this and analytics reporter, along with [this blogpost](http://sites.usa.gov/digitalgov/2016/01/07/tips-for-adapting-analytics-usa-gov-from-tennessee-boulder-and-philadelphia/) seem to have it covered.  I'm going to go ahead and close this.
