### ISSUE TITLE
Publish browser stats for Microsoft Edge

### ISSUE THREAD

**Issue by konklone** [18F/analytics.usa.gov#137]
We have to whitelist individual browsers and versions, so to keep on top of IE we'll want to proactively whitelist "12", "13", "14", etc. I think the Technical Preview will be "TP", but it's not unlikely we'll find an example already in the analytics.

**Comment by konklone** [comment]
This was added to the data, but as a Browser and not an IE Browser Version: https://github.com/18F/analytics-reporter/issues/83

**Comment by JuliaWinn** [comment]
https://github.com/18F/analytics.usa.gov/pull/260

**Comment by konklone** [comment]
Closed by #260.
