### ISSUE TITLE
Fix White House Petition links in the general case

### ISSUE THREAD

**Issue by kaitlin** [18F/analytics.usa.gov#138]
For instance, one of the top links right now is:
https://petitions.whitehouse.gov/petition/demand-brooklyn-district-attorney-kenneth-p-thompson-withdraw-indictment-against-asian-minority/G26sxfMP

But the actual link from the analytics dashboard is:
https://petitions.whitehouse.gov/petition/demand-brooklyn-district-attorney-kenneth-p-thompson-withdraw-indictment-against-asian-minority/g26sxfmp

Which lowercases the capitalized letters at the end, resulting in a 404 on the We the People site. We should maybe try and find some way of preserving the case to prevent dead links.

**Comment by rypan** [comment]
Some of the links are capitalized: `http://www.irs.gov/Individuals/Electronic-Filing-PIN-Request` - but I think that might be done manually via https://github.com/GSA/analytics.usa.gov/issues/125. @konklone would know more.

**Comment by konklone** [comment]
I'm going to tackle a generalized function for WH Petitions, for now. For the rest, I've filed https://github.com/GSA/DAP-Gov-wide-GA-Code/issues/10 to take care of it at the source.

**Comment by cew821** [comment]
One new one is broken: https://petitions.whitehouse.gov/petition/take-out-alejandro-garc%C3%ADa-padilla-governorship-puerto-rico-now/b0jgb8sv

**Comment by cew821** [comment]
One note: Ryan discovered that Petitions doesn't actually need the trailing Hash to resolve correctly. I don't know if this would actually be easier or not, but one solution to fix all the Petitions would be to strip anything after the trailing  /petition/**any letters**/ 

(i don't speak Regex well)

So like this: https://petitions.whitehouse.gov//petition/help-make-united-healthcare-pay-my-mothers-treatment-save-her-life/0qwsDWgk

would become this:

https://petitions.whitehouse.gov//petition/help-make-united-healthcare-pay-my-mothers-treatment-save-her-life/

**Comment by konklone** [comment]
We removed the exceptions for whitehouse.gov.
