### ISSUE TITLE
Convert remaining reports over to new whitelisted profile

### ISSUE THREAD

**Issue by konklone** [18F/analytics.usa.gov#141]
I believe it was mid-January when the whitelisted profile started gathering data. When appropriate, switch...

- [ ] The 30 day reports. (now)
- [ ] The 90 day reports. (mid-April)

...to using the new profile.

**Comment by gbinal** [comment]
@konklone - it seems safe to close this issue.  That cool with you?

**Comment by konklone** [comment]
Yep.
