### ISSUE TITLE
Encoding issue in JSON data files?

### ISSUE THREAD

**Issue by mheadd** [18F/analytics.usa.gov#149]
Some of the data in the static JSON files seems to have a character encoding issue. Example [here](https://analytics.usa.gov/data/live/top-pages-realtime.json):

```
{
    page: "usajobs.gov/search/getadvancedsearchresults",
    page_title: "USAJOBS - The Federal Governmentâ€™s Official Jobs Site",
    active_visitors: "434"
}
```

**Comment by kyledreger** [comment]
@mheadd See 18F/analytics-reporter#83 for a possible fix.

**Comment by gbinal** [comment]
@jmhooper - Can you confirm if https://github.com/18F/analytics-reporter/pull/128 resolved this issue along with https://github.com/18F/analytics-reporter/issues/83 ?
