### ISSUE TITLE
allow export of stats for all government "kids" pages 

### ISSUE THREAD

**Issue by sbma44** [18F/analytics.usa.gov#153]
ideally everything with "kid" in it. I'd settle for `/kid'?[sz]\s+[ck]orner/`, though.

**Comment by konklone** [comment]
:+1: :100:

**Comment by leahbannon** [comment]
Honestly curious and not that you need to justify, but... why?

**Comment by gbinal** [comment]
I'm not sure we want to prioritize just this but agree with enabling this and other such queries.  

The [proiferation of kids sections on .gov sites](https://www.google.com/search?q=inurl%3Akids+site%3A.gov&oq=inurl%3Akids+site%3A.gov&aqs=chrome..69i57j69i58.8015j0j7&sourceid=chrome&es_sm=91&ie=UTF-8) is really quite crazy.

**Comment by sbma44** [comment]
@leahbannon mostly this is a joke, but more seriously: it would be nice to be able to draw conclusions about the ROI on some common, kooky things that agencies do. Right now analytics.usa.gov is great for understanding the sites that the public finds most useful and how they choose to access them; it's less useful for cutting fat.

**Comment by nsinai** [comment]
This does beg the question about the least visited pages and domains...

**Comment by NoahKunin** [comment]
Seriously, GitHub needs to implement star-ing issues stat. But until they do:

:star2: :star: :star2: :star: :star2: :star: :star2: :star: :star2: :star: :+1:

**Comment by gbinal** [comment]
With the [expanded data feeds](https://www.digitalgov.gov/2015/12/01/analytics-usa-gov-new-features-and-more-data/), this should now be possible.  

I'm going to go ahead and close.  Thanks for the interest!
