### ISSUE TITLE
Add a note about javscript being required to display any data

### ISSUE THREAD

**Issue by timwood** [18F/analytics.usa.gov#165]
Not a lot of users out there browse without javascript today, but some still do. Might be worth adding a note about requiring JS to see any data.

P.S. Love what you've built here! Cannot wait till we get past tax season to see who is most visited throughout the rest of the year.

**Comment by gbinal** [comment]
We don't have plans to revisit the design anytime soon, so I'm going to close this issue for now.  It'll still have the `Backlog` label on it in case we want to revisit and open.
