### ISSUE TITLE
An API or feed of pages that have ever appeared in the Realtime Top 20

### ISSUE THREAD

**Issue by konklone** [18F/analytics.usa.gov#169]
So this requires more infrastructure than is currently there, but this project is begging for an API or feed of pages that make it into the Top 20.

The use case I want to empower is being notified whenever a URL makes it into the Top 20 that's never been seen before. I think **a ton** of people would use this, and it would make an amazing IFTTT recipe. (We could output the feed in RSS form so that a recipe could be made without needing to build a new channel.)

It would require storing which pages have made it into the Realtime Top 20 before, as I think the Google Analytics API would be insufficient for figuring out historical real-time chart-topping at any given time. 

Like the current data, this could probably be hosted statically or dynamically.

But no matter which approach we take, something has to be just polling our own real-time API every minute and saving pages that appear there into something. Ideally, this list of pages would be versioned as a JSON or YAML file somewhere.

**Comment by dwillis** [comment]
+1 this would be very useful

**Comment by konklone** [comment]
I should also note that it's possible for any third party to construct this today, by using the data we currently publish .

**Comment by wslack** [comment]
Would this be of significant interest that we could ask a few CSCI departments about building it, or making that a possible project?

**Comment by konklone** [comment]
CSCI?

**Comment by wslack** [comment]
Computer Science

**Comment by konklone** [comment]
It seems smaller-scale than what would be worth engaging an academic office for. It would make for a pretty great hackathon project. cc @ultrasaurus Unless I get to it first in my personal time!

**Comment by nsinai** [comment]
Why don't you tag it with help wanted?  Or think about a tag for CS and engineering students?

**Comment by wslack** [comment]
@konklone can you do that? I don't have tag privileges on this repo.

**Comment by konklone** [comment]
https://twitter.com/topfederalsites is currently totally doing this using our existing data (with an [RSS feed](https://stvnrlly.com/rss/topfederalsites.xml)), and it's doing a great job. We would still benefit by performing this work in-house, I think, offering a .gov RSS feed. It would also allow us to build on top of it -- such as grabbing a snapshot of real-time referrers at the moment a site hits the top 20 for the first time.

**Comment by onceuponatimeforever** [comment]
Sounds like a cool project for folks who like APIs. I'd like to help or collaborate on this.

I have questions on requirements. Do you know if this project will be a separate github repo or do you hope to have this a distinct database-backed feature in this repo? Do you have requirements on what database to use? or what the tools should be generating this RSS feed?

**Comment by konklone** [comment]
I'd love to hear from others, like @laurenancona and @stvnrlly and @geramirez and @JuliaWinn, but it seems to me like it'd be most easily done as a standalone app with a very lightweight database that "watched" the public feed and used a local database to decide what it's seen before.

This also seems like something that could be done using a generic `watching`->`feed` framework, though the only one I know of offhand is [`huginn`](https://github.com/cantino/huginn), which is quite hefty.

**Comment by konklone** [comment]
@onceuponatimeforever It's also worth noting that an additional app like this would need some team and project owner consensus, as well as other operational and security steps, before we could officially deploy it. But the above is what I think is the most feasible path.

**Comment by onceuponatimeforever** [comment]
https://github.com/tschellenbach/Stream-Framework is another framework for generating feed and requires Redis or Cassandra.

**Comment by konklone** [comment]
That project looks really cool and thoughtful, with infrastructure choices I respect.

**Comment by stvnrlly** [comment]
I like the idea of a standalone app that can serve as a sort of add-on (or suite of add-ons) to the existing `analytics-reporter` -> `analytics.usa.gov` pipeline, for those who want to create second-level reports. New sites in the top 20 would be one such report; other such reports could be practical things like checking for broken links or HTTPS coverage in the top 20, or something fun like non-new sites receiving an unusually high number of visitors.

**Comment by gbinal** [comment]
@jmhooper, @tdlowden, @laurenancona - we should factor in this thinking into what we release in the API work that is ongoing.  

For now though, I'm going to go ahead and close this issue in favor of https://github.com/18F/analytics.usa.gov/issues/169.
