### ISSUE TITLE
Referring Search Engine

### ISSUE THREAD

**Issue by AdamSC1-ddg** [18F/analytics.usa.gov#176]
I was hoping this project could be expanded to show referring sites and search engines such as Google, Bing, DuckDuckGo, Yahoo and Yandex!

**Comment by leahbannon** [comment]
+1

**Comment by AdamSC1-ddg** [comment]
Wanted to see if there were any further thoughts on integrating this suggestion! Think it could be very useful data!

**Comment by smarina04** [comment]
Thanks for your comment @AdamSC1-ddg . Could you explain how this specific data be of use to you?

**Comment by gbinal** [comment]
FYI, top traffic sources is now in the data downloads section.
