### ISSUE TITLE
consider an about page 

### ISSUE THREAD

**Issue by gbinal** [18F/analytics.usa.gov#178]
I wonder if it makes sense to create `/about` to allow for more project  information and background.  

For instance, it might be helpful to link to the other federal analytics dashboards we come across.  Offhand, I know of: 
* http://www.cdc.gov/metrics/
* http://dashboard.si.edu/

**Comment by konklone** [comment]
That's a great idea. :+1:

**Comment by gbinal** [comment]
We're not on track to do this anytime soon, so I'm going to go ahead and close for now.
