### ISSUE TITLE
Visits from Government or Public networks

### ISSUE THREAD

**Issue by shawngm** [18F/analytics.usa.gov#179]
It would be great to know how many of the visits are from Government or Public service providers.

**Comment by konklone** [comment]
This is a great idea, and it's being discussed. As you might guess though, it's a challenging thing to ascertain with a high degree of certainty. Thanks for raising the issue -- hopefully we'll have more detail for you one way or the other.

**Comment by shawngm** [comment]
Awesome.  It's definitely a brilliant project so far!

**Comment by tdlowden** [comment]
Appreciate you raising this issue, and it continues to come up in discussion. Being that we don't collect IP addresses, what @konklone mentioned still holds true, and it's difficult to do this with certainty. But we're keeping it in our minds moving forward.
