### ISSUE TITLE
Rethink "today" bar chart

### ISSUE THREAD

**Issue by konklone** [18F/analytics.usa.gov#181]
The bar chart suffers delays that were tolerable at launch, but are becoming less tolerable over time.

The [Real Time API](https://developers.google.com/analytics/devguides/reporting/realtime/dimsmets/) doesn't seem to allow any way to get at historical data (not what it's designed for), so there's no way I'm aware of for us to pull the data in that bar chart in a timely way in a single Google Analytics report call.

We could just remove the bar chart.

But another idea I like is making the chart simply a representation of the Big Real-Time Number over time. This would change it from cumulative visits within an hour to average people online over the course of an hour, but it'd likely be a lot more sensical, since the big number is on top of it. We could also change the granularity from per-hour to per-minute or per-5-minutes to show a smoother graph.

However, so it's clear, the above idea requires a bit of change to the system, as it means we need to keep archival data. Right now all we're doing is making a single request to the GA API per chart/table, and then rendering its results. A chart that shows data over time would require us to create a file that's sort of a running amalgam of previous reports.

**Comment by tdlowden** [comment]
see #395, as well

**Comment by gbinal** [comment]
I've added this to the backlog but am going to go ahead and close since we don't know when we'll be further refining the design.
