### ISSUE TITLE
Add Executive Branch Department Facet for Device, Browser, and OS Analytics

### ISSUE THREAD

**Issue by patricknowlan** [18F/analytics.usa.gov#187]
This would allow the public to view the analytics for domains grouped by parent department. It would nice to tell a story about what executive departments are behind on their tech and... we might get a better view into who is using / supporting IE 7 and rally to drive that department to update their browsers! I realize these metrics are based off of public traffic so the stats might be skewed unless there is a way to also filter on public and/or government traffic? My current problem is I don't have department specific stats to point to when deciding on whether or not to support IE 8 on a government app.

**Comment by gbinal** [comment]
Launched with this release - http://sites.usa.gov/digitalgov/2016/02/18/analytics-usa-gov-now-with-agency-specific-dashboards/.  

More agencies to come.

**Comment by patricknowlan** [comment]
:+1:
