### ISSUE TITLE
Plot out location widget functionality

### ISSUE THREAD

**Issue by gbinal** [18F/analytics.usa.gov#199]
What should be expressed in a location widget?

**Comment by tdlowden** [comment]
DAP data can provide: Continent, country, city, and sub-continent. I think country and city are really the two useful data points.

Most of the visits come from from the USA UNTIL we get into the wee hours of the morning. If we have the capability of doing real-time country or city location, I think it'd be great. In the case we can't do real-time, I am nearly positive we could do it by hour, and post info that updates hourly for the last hour. My point here is that if we do something over the span of 24 hours or longer, it'll always have USA as the top country, whereas if we can chunk it a bit more, we'll get more nuance in terms of the countries that view gov sites while we're sleeping.

IMO, listing countries in a regular old list is fine. A probably very difficult design feature would be to have a map of the US and denote top cities in some way. Alternatively, listing top cities (maybe 10) wouldn't be the end of the world.

**Comment by gbinal** [comment]
A mockup:  
![screen shot 2015-10-06 at 12 21 20 pm](https://cloud.githubusercontent.com/assets/633088/10314817/d3047e1e-6c24-11e5-9d47-501a9852f04b.png)

**Comment by gbinal** [comment]
A question to ask:  
* Should this go above or below Devices/Browsers/OS?

**Comment by gbinal** [comment]
An integrated look of both widgets in the page:  

![mockup-analytics usa gov-gb](https://cloud.githubusercontent.com/assets/633088/10354845/9333c2fe-6d32-11e5-9515-388e99384189.png)
