### ISSUE TITLE
Plot out downloads widget functionality

### ISSUE THREAD

**Issue by gbinal** [18F/analytics.usa.gov#200]
What should be expressed in a downloads widget?

**Comment by tdlowden** [comment]
Event data is laid out in this fashion within DAP:

Event Category>>Event Action>> Event Label

and plays out as

Download>>pdf>>http://www.socialsecurity.gov/forms/ss-5.pdf

As far as I'm concerned, I have no issue reporting for Event Category=download and then listing the top 10 or 20 labels. Separating by Event Action (i.e. extension in this case) seems too complicated. I don't care if it is a pdf or doc or even mp3.

To confound this, we also have an "outbound download" category, which accounts for links to files that are hosted within a different domain than the one the page with the link is on.

For our purposes, I think it'd be prudent of us to attempt to combine those two categories to see the whole of things downloaded from government webistes.

**Comment by gbinal** [comment]
The text for each entry could be structured like this:  

* ss-5  >>  www.socialsecurity.gov
* n-400  >>  www.uscis.gov
* DV-2017%20Instructions%20and%20FAQs.pdf  >>  travel.state.gov

**Comment by gbinal** [comment]
Questions to ask:  
* Are there 
* Should we convert e.g. `%20` to ` `.

**Comment by gbinal** [comment]
Where page title can be found...

![screenshot 2015-10-07 at 11 49 18 am](https://cloud.githubusercontent.com/assets/633088/10342950/88c661e4-6ce9-11e5-820e-b7615bae64b6.png)

**Comment by tdlowden** [comment]
Maybe rather than the domain, we can include links to both the download file and the page from which it is downloaded. I just hope the API has the ability to query this associated page with the event label in tandem.

**Comment by ramirezg** [comment]
@tdlowden looks like the api can get the page url and title on which the event occurred. [Here's](https://github.com/18F/analytics-reporter/compare/master...ramirezg:new_reports#diff-542b3fb88b5c1dc5164494a4ee538b99R221) the report that worked for me.

Thoughts on the time frames and update frequency?

**Comment by tdlowden** [comment]
@ramirezg that's great news! I think the idea would be that we'd mimic the realtime, 7 day, and 30 day setup we already have. currently, the realtime info updates every minute. So, similar to the pages/sites, I think we'd have to use the real-time API and the report API

**Comment by gbinal** [comment]
Great point, @tdlowden.  I'd actually advise that the filename link to the downloadable file and the domain link to the page.  That make sense?

**Comment by tdlowden** [comment]
@gbinal definitely makes sense, I just love the descriptive nature of the page title. I for sure htink we should link to the file itself, but i am a proponent of the other visible piece being the actual page title. It seems like for the majority of them, the page title has some indication of agency.  

![image](https://cloud.githubusercontent.com/assets/6556888/10347734/5d348a32-6d03-11e5-9a16-6d320127dbc9.png)

**Comment by gbinal** [comment]
Here's a mockup of what I'm proposing:  

![screen shot 2015-10-07 at 3 12 26 pm](https://cloud.githubusercontent.com/assets/633088/10348235/e395fce4-6d05-11e5-81c8-f5645cf2b17f.png)

And more up close:  

![screen shot 2015-10-07 at 3 12 40 pm](https://cloud.githubusercontent.com/assets/633088/10348238/ec90c568-6d05-11e5-9e5b-fded204d9a20.png)

**Comment by gbinal** [comment]
An integrated look of both widgets in the page:  

![mockup-analytics usa gov-gb](https://cloud.githubusercontent.com/assets/633088/10354845/9333c2fe-6d32-11e5-9515-388e99384189.png)

**Comment by smarina04** [comment]
Folks,

Not sure I'm a fan of the new "domains" report and the removal of the page
titles. I recommend those be added back.

Perhaps the section titles could be "top 20 Pages" and "top 10 File
Downloads".... just thinking that  "Domains" sounds too web techy and
"downloads" on its own is visually a bit confusing with section title
"download the data".

Thanks,
Marina

**Comment by gbinal** [comment]
Sorry for any confusion.  The domains section on the right of analytics.usa.gov is the same in this.  It's page titles are still there (the screenshot above is just on the 7 days view).  

This is all just brainstorming.  I'm setting up a time for us all to connect on Tuesday, so we'll be able to get into together and figure out.
