### ISSUE TITLE
link and display the expanded data feeds 

### ISSUE THREAD

**Issue by gbinal** [18F/analytics.usa.gov#214]

**Comment by gbinal** [comment]
This will need to be able to expand to the new bulk data feeds for location and downloads when we have that ready.

**Comment by JuliaWinn** [comment]
https://github.com/18F/analytics.usa.gov/pull/227

**Comment by konklone** [comment]
Up on https://pages.18f.gov/analytics.usa.gov/

**Comment by konklone** [comment]
Still need to display the expanded data feeds.

**Comment by konklone** [comment]
Done.
