### ISSUE TITLE
add location widget to staging

### ISSUE THREAD

**Issue by gbinal** [18F/analytics.usa.gov#228]

**Comment by JuliaWinn** [comment]
<img width="575" alt="screen shot 2015-10-22 at 10 13 28 am" src="https://cloud.githubusercontent.com/assets/821557/10667494/a82a8124-78a5-11e5-9b90-cfce4e5fca37.png">
This is what visitors over the past 90 days looks like

**Comment by JuliaWinn** [comment]
<img width="578" alt="screen shot 2015-10-22 at 10 12 31 am" src="https://cloud.githubusercontent.com/assets/821557/10667501/b32715ba-78a5-11e5-9f5a-54bc4093eeae.png">
This is what the realtime data looks like

**Comment by JuliaWinn** [comment]
Since the all the realtime data is the same, I am now looking into switching this to raw numbers.

**Comment by tdlowden** [comment]
+1 @JuliaWinn

**Comment by JuliaWinn** [comment]
<img width="569" alt="screen shot 2015-10-22 at 10 48 36 am" src="https://cloud.githubusercontent.com/assets/821557/10668481/7d809314-78aa-11e5-9565-f4c58df99de5.png">

Actually it looks like after making some changes in the script to correctly parse the realtime data we have some coherent numbers, so we can stick with percents.

**Comment by JuliaWinn** [comment]
Latest code pushed, seems to be functioning. There is only a minor css bug, the borders around "Visitors Online Now" are not showing up because for some reason the <h3> area is seen as extending far up the page. @shawnbot any chance you have a couple minutes take a look to see what's going on?

**Comment by konklone** [comment]
Up on https://pages.18f.gov/analytics.usa.gov/.
