### ISSUE TITLE
href to nlm.nih.gov is http instead of https

### ISSUE THREAD

**Issue by brendansudol** [18F/analytics.usa.gov#231]
it looks like the link in the "Top 20" domains table for "nlm.nih.gov" uses http instead of https in the href, which throws a "this connection is untrusted" message in firefox (and something similar in chrome); here's a screenshot: http://cl.ly/image/2N1H3n2h2O1r

should be a quick fix :)

**Comment by brendansudol** [comment]
ah, sorry, please disregard last comment -- the issue is unrelated to the href. it looks like that site (nlm.nih.gov) has an "invalid security certificate" (Error code: ssl_error_bad_cert_domain says firefox), which is completely unrelated to analytics.usa.gov

keep building this awesome thing!

**Comment by konklone** [comment]
Well, it seems like NIH could make their server configuration more flexible, to handle the URL with or without the `www` prefix. Thanks for taking a look through it!
