### ISSUE TITLE
"Other" is listed twice under "Operating Systems"

### ISSUE THREAD

**Issue by JuliaWinn** [18F/analytics.usa.gov#235]
Each has different percent values.

**Comment by JuliaWinn** [comment]
<img width="744" alt="screen shot 2015-10-28 at 12 31 21 pm" src="https://cloud.githubusercontent.com/assets/821557/10795367/d4eecc50-7d6f-11e5-99fd-edf32f983dcb.png">

**Comment by JuliaWinn** [comment]
![screencapture-127-0-0-1-4000-1446049984369](https://cloud.githubusercontent.com/assets/821557/10795428/1ee0f716-7d70-11e5-9067-4842f3524171.png)

The problem is that when the "Other" bug is fixes this throws off the alignment of the columns.

**Comment by JuliaWinn** [comment]
![screencapture-127-0-0-1-4000-1446050100620](https://cloud.githubusercontent.com/assets/821557/10795481/607b4c12-7d70-11e5-9db2-1839e8db5a3b.png)

The misalignment can be remedied somewhat by switching the positions of "Operating Systems" and "Browsers" but this doesn't really solve the problem.

**Comment by JuliaWinn** [comment]
@shawnbot what are your thoughts?

**Comment by konklone** [comment]
Fixed by #236.
