### ISSUE TITLE
Some live data JSON 404s

### ISSUE THREAD

**Issue by chrishepner** [18F/analytics.usa.gov#240]
Hi,

I'm currently seeing 404s when following the links for certain live data (e.g., "Top 100 downloads right now (Updated every minute)"):

https://analytics.usa.gov/data/live/top-downloads-realtime.json
https://analytics.usa.gov/data/live/top-downloads-30-days.json
https://analytics.usa.gov/data/live/top-cities-90-days.json
https://analytics.usa.gov/data/live/top-countries-90-days.json

**Comment by konklone** [comment]
Ah, our bad, we posted that link prematurely -- we're about to remove that as a data source (it doesn't make sense to publish so many different time windows for the same data) and publish some new links with extended data. I'll resolve this ticket once we've done that.

**Comment by konklone** [comment]
This should be resolved now: https://analytics.usa.gov
