### ISSUE TITLE
404 error on city data link

### ISSUE THREAD

**Issue by amylibrarian** [18F/analytics.usa.gov#241]
404 error at 9:10am CT: 
https://analytics.usa.gov/data/live/top-cities-90-days.json

**Comment by konklone** [comment]
Ah, our bad, we posted that link prematurely -- we're about to remove that as a data source (it doesn't make sense to publish so many different time windows for the same data) and publish some new links with extended data. I'll resolve this ticket once we've done that.

**Comment by amylibrarian** [comment]
Thank you for the speedy response! Just an FYI that I think academic and special librarians of many disciplines would appreciate an informational session on Analytics.usa.gov. For example, Agriculture librarians could learn how to track usage of USDA webpages. I wrote this article [Using Analytics.usa.gov to Learn about Traffic on Government Websites http://hdl.handle.net/11299/175123] recently. I also mentioned Analytics.usa.gov and NASA.gov web traffic when talking about Mars/NASA in this video [Read This Book! - Books about Mars https://youtu.be/Sj6j9pAWpf8]. Let me (@amylibrarian on Twitter; aspringe@umn.edu) know if you are interested in collaborating on a virtual informational session for FDLP Academy (http://www.fdlp.gov/about-the-fdlp/fdlp-academy).

**Comment by konklone** [comment]
This should be resolved now: https://analytics.usa.gov
