### ISSUE TITLE
Could you make the "top pages" tabs bookmarkable?

### ISSUE THREAD

**Issue by Klortho** [18F/analytics.usa.gov#250]
Right now, if I go straight to https://analytics.usa.gov/#top-pages-7-days, for example, I still see the main page. It would be nice if it would go straight to that "tab".  I tried to fix it myself, but your code is a little to sophisticated for me.

**Comment by gbinal** [comment]
This is definitely a good idea and worth doing but our foreseeable roadmap is focused heavily on refining the site operation, so we likely won't be further expanding the GUI's functionality. If we do though, we'll include this as a potential feature to add.

Thanks.
