### ISSUE TITLE
Remove .swf files from the Downloads table

### ISSUE THREAD

**Issue by konklone** [18F/analytics.usa.gov#251]
Though it's useful to keep this stuff in GA, since .swf files don't run the Google Analytics code, but if we're trying to show what people are downloading, .swf doesn't fit. And since the top item is a .swf, and far away the top one, it's distorting our numbers.

So far, we haven't seen anything else worth explicitly filtering out. It's ideal to do this at the query level, if at all possible.

**Comment by gbinal** [comment]
Here are other filetypes that we may want to filter out.  What do you think?  

* .jsp
* .do
* .htm
* .html
* .asp
* .aspx
* .cfm
* .php

**Comment by konklone** [comment]
The extensions currently logged as "downloads" by the DAP are:

> EXTS: 'doc|docx|xls|xlsx|xlsm|ppt|pptx|exe|zip|pdf|js|txt|csv|dxf|dwgd|rfa|rvt|dwfx|dwg|wmv|jpg|msi|7z|gz|tgz|wma|mov|avi|mp3|mp4|csv|mobi|epub|swf|rar',

https://github.com/digital-analytics-program/gov-wide-code/blob/master/Universal-Federated-Analytics.js#L38

So the ones you listed above won't be an issue.

**Comment by gbinal** [comment]
Ah - that's great to know.  Skimmed through that but what about `.js`?  I'd tend to think that that wouldn't be something we'd think of as a 'download'.

**Comment by gbinal** [comment]
Actually, another thought:  Are we sure that the whitelist of extensions being logged as "downloads" by the DAP will be still hold if we decide to pull in the `Outbound Downloads` and `Downloads` event categories as raised in https://github.com/18F/analytics.usa.gov/issues/254?  

I believe I've seen file extensions other than those listed above in those event categories.

**Comment by gbinal** [comment]
@geramirez - does ^^^ question make sense?  I saw your answer over in #254 but don't think this is quite the same.

**Comment by gbinal** [comment]
We think this should be done at the query level.

**Comment by gbinal** [comment]
Update: we're not going to worry about `.js`.

**Comment by geramirez** [comment]
swf files removed on on the Analytics Reporter side - 18F/analytics-reporter/pull/126

**Comment by konklone** [comment]
@geramirez I wouldn

**Comment by konklone** [comment]
Ugh, sorry for the GitHub mistakes. I see it's updated on analytics.usa.gov now -- thanks, @geramirez!
