### ISSUE TITLE
Publish blog post about locations, downloads, and bulk data

### ISSUE THREAD

**Issue by konklone** [18F/analytics.usa.gov#253]
We need to get the blog post drafting/approval process started at 18F to talk about the additional data we're showing/publishing on locations, downloads, and bulk data.

**Comment by gbinal** [comment]
[Here's a google doc](https://docs.google.com/document/d/1bP4U_4aV380tKRI6PUkfn7KN58I3GyIHqOoW8-aRATU/edit).  @tdlowden, @konklone - please go to town.

**Comment by gbinal** [comment]
This is drafted.  We now need to review and blog it.

**Comment by gbinal** [comment]
http://www.digitalgov.gov/2015/12/01/analytics-usa-gov-new-features-and-more-data/
