### ISSUE TITLE
Confirm source of the File Downloads widget

### ISSUE THREAD

**Issue by gbinal** [18F/analytics.usa.gov#254]
Do we know if the data feed is pulling in the `Outbound Downloads` and `Downloads` event categories along with the `Download` categories?  Looking at the Top Events section, these appear to be substantial enough to include (screenshot below).    

![screen shot 2015-11-11 at 2 33 39 pm](https://cloud.githubusercontent.com/assets/633088/11102352/98054734-8881-11e5-9276-42e300777e5b.png)

**Comment by gbinal** [comment]
@JuliaWinn - any thoughts on this?

**Comment by JuliaWinn** [comment]
@geramirez, thoughts? (since I believe you wrote the code)

**Comment by geramirez** [comment]
@gbinal @JuliaWinn the report should query any event categories that [regex match `/ownload/`](https://github.com/18F/analytics-reporter/blob/master/reports/usa.json#L193) so `Outbound Downloads`,  `Downloads` and `Download` should be covered.

**Comment by geramirez** [comment]
Just letting ya'll know. I checked the query and found that all the categories were included.
