### ISSUE TITLE
Include fake test data for local dev 

### ISSUE THREAD

**Issue by onceuponatimeforever** [18F/analytics.usa.gov#265]
Would be nice for developers to be have access to a common directory of fake test data to populate the local dev version of the site. 

As a new contributor, I tried the following but got 404s, because the test json is missing: 

```
3:51 $ serve --cors
serving /Users/susantan/Projects/analytics.usa.gov on port 3000
GET /realtime.json 404 24ms
GET /today.json 404 17ms
GET /top-pages-realtime.json 404 6ms
GET /realtime.json 404 2ms
GET /today.json 404 1ms
GET /devices.json 404 0ms
GET /browsers.json 404 0ms
GET /ie.json 404 1ms
GET /os.json 404 1ms
GET /windows.json 404 2ms
GET /top-cities-realtime.json 404 0ms
GET /top-countries-realtime.json 404 1ms
GET /top-countries-realtime.json 404 2ms
GET /top-pages-realtime.json 404 2ms
GET /top-domains-7-days.json 404 2ms
GET /top-domains-30-days.json 404 1ms
GET /top-downloads-7-days.json 404 1ms
GET /realtime.json 404 1ms
GET /today.json 404 2ms
GET /devices.json 404 1ms
GET /browsers.json 404 1ms
```

**Comment by konklone** [comment]
I agree entirely. If you feel like generating some, PR welcome, otherwise we'll hopefully get to this during development at some point. It'd make life easier for us too.

**Comment by onceuponatimeforever** [comment]
It's so convenient that all these json files are live. ie https://analytics.usa.gov/data/live/top-cities-realtime.json. :smile_cat:  I plan to 

1. copy & paste those json files into a new `fake_data` directory.
2. provide instructions on README for new contributors to manually switch out the url links in the `index.js` to refer to the test data. ie: `http://localhost:3000/fake_data/real_time.json`.

**Comment by konklone** [comment]
@onceuponatimeforever If you don't mind me asking, is there a particular project you're using this for? We always love to hear about where our open source work ends up.

**Comment by onceuponatimeforever** [comment]
@konklone No particular project in mind. I'm working on the 24Pull Requests challenge this month. :)

**Comment by konklone** [comment]
Well we're very happy you picked our project to contribute, thank you!

**Comment by gbinal** [comment]
What @konklone said!  Thanks so much, @onceuponatimeforever!!!  We really appreciate your time and help. :us:  :muscle: :computer:

**Comment by onceuponatimeforever** [comment]
No problem, let me know if you have code review feedback, I respond fairly quickly in a day.

**Comment by konklone** [comment]
Thanks for doing this! The team was happy with this approach and grateful for the contribution.
