### ISSUE TITLE
Work out api key solution

### ISSUE THREAD

**Issue by gbinal** [18F/analytics.usa.gov#270]
@konklone and @geramirez - if you two can't work out a solution for this by Sprint 5, let's partner with an agency to employ a work around.  @tdlowden - we'd need your help thinking about who would be a particularly good partner for this.

**Comment by geramirez** [comment]
I've half of the realtime api calls to work with the new key and check that the solution is working.

**Comment by geramirez** [comment]
Also, let's note that this is temporary hack.
