### ISSUE TITLE
Deploy fails with -M option. (s3cmd: error: no such option: -M)

### ISSUE THREAD

**Issue by bryanhirsch** [18F/analytics.usa.gov#315]
When I try to deploy my jekyll-generated site to S3 using the Makefile's deploy command, `s3cmd` complains and the deploy fails:

```
s3cmd: error: no such option: -M
```

When I remove the `-M` option (e.g. https://github.com/massgov/analytics.mass.gov/commit/7953856a22a4c230626d3f40225e7a764883a576) things seem to get pushed up to S3. What is the `-M` flag supposed to do?

**Comment by konklone** [comment]
What version of `s3cmd` are you using? When I run `s3cmd --help`, I see:

```
 -M, --guess-mime-type
                        Guess MIME-type of files by their extension or mime
                        magic. Fall back to default MIME-Type as specified by
                        --default-mime-type option
```

We were using it for this purpose, but as you can see from the subsequent `s3cmd` statements that were appended to it, it seemed to stop working at some point and so we added commands that explicitly set mime types for some files.

This led us to abandon `s3cmd` in favor of the [official AWS CLI for our Pulse project](https://github.com/18F/pulse#configure-the-aws-cli), which is what we should probably do here at our next opportunity.

**Comment by konklone** [comment]
Oh, and I am using `s3cmd` version 1.5.2:

```
$ s3cmd --version
s3cmd version 1.5.2
```

**Comment by gbinal** [comment]
@bryanhirsch - any thoughts on ^^^^?

**Comment by gbinal** [comment]
I'm going to go ahead and close this.  Holler if you have further followup, @bryanhirsch.
