### ISSUE TITLE
Investigate `(other)` pages/content drilldown 

### ISSUE THREAD

**Issue by gbinal** [18F/analytics.usa.gov#320]
![screen shot 2016-03-02 at 12 48 38 pm](https://cloud.githubusercontent.com/assets/633088/13469392/3636a268-e075-11e5-83ce-1bec1e202789.png)

![screen shot 2016-03-02 at 12 48 58 pm](https://cloud.githubusercontent.com/assets/633088/13469388/313a8f86-e075-11e5-96ab-b36505461ccf.png)

**Comment by tdlowden** [comment]
This is a cardinality issue:

https://support.google.com/analytics/answer/1009671?hl=en

Basically, Google aggregates a bunch of the long tail at the end of a high-cardinality list. You can alleviate with unsampled reports.

**Comment by gbinal** [comment]
Ah - gotcha.  Thanks!
