### ISSUE TITLE
A view with top site per department

### ISSUE THREAD

**Issue by llastowka-usgs** [18F/analytics.usa.gov#330]
Now that the post office is on board, the top 20 list is saturated with their popular pages. How about a view that has the top site per department? 

Thanks! Lynda (from earthquake.usgs.gov who are now off the top list (until the next big quake) )

**Comment by tdlowden** [comment]
Hi Lynda. We offer a type of that suggestion with the agency-specific pages. analytics.usa.gov/interior still has earthquake.usgs.gov as the top page.

**Comment by llastowka-usgs** [comment]
Thanks! I saw that, I just thought it might be interesting to aggregate/compare the top sites across departments. Just a suggestion!  I enjoy the DAP info and site, thank you!

**Comment by tdlowden** [comment]
Closing for now, as we are continually expanding the agency pages.
