### ISSUE TITLE
prototype the gsa-hosted analytics api 

### ISSUE THREAD

**Issue by gbinal** [18F/analytics.usa.gov#331]
following up from https://github.com/18F/analytics.usa.gov/issues/324

**Comment by cacraig** [comment]
See. #152

**Comment by gbinal** [comment]
This is on hold while we figure out the transition to cloud.gov, so I'm going to remove from this sprint for now.

**Comment by gbinal** [comment]
This is under way and should take into account the good ideas at https://github.com/18F/analytics.usa.gov/issues/169.

**Comment by gbinal** [comment]
done!
