### ISSUE TITLE
Make relationship between top pages/domains and time series clearer (screenshot)

### ISSUE THREAD

**Issue by hbillings** [18F/analytics.usa.gov#345]
This will make it less confusing when the data points change from pages on the "now" tab to domans on the 7- and 3-day tabs.
Also move the disclaimer about time series from the About footer to the tabs.
https://cloud.githubusercontent.com/assets/509309/13885602/4880fe26-ed01-11e5-839e-3d98a256c963.png

**Comment by tdlowden** [comment]
After implementing this, we made a call to leave the language as was previously.
