### ISSUE TITLE
Remove bars from "Cities"

### ISSUE THREAD

**Issue by hbillings** [18F/analytics.usa.gov#346]
The numbers are all so small that the bars feel visually like extra whitespace. "Cities" could effectively adopt the style used for the country breakdown.
https://cloud.githubusercontent.com/assets/509309/13887316/0e88b2f6-ed09-11e5-8528-e35a7f4001c0.png

**Comment by gbinal** [comment]
I've added this to the backlog but am going to go ahead and close since we don't know when we'll be further refining the design.
