### ISSUE TITLE
Address excess whitespace

### ISSUE THREAD

**Issue by hbillings** [18F/analytics.usa.gov#347]
particularly around the location charts. One potential way to do this would be to break the "US" and "International" bars into their own column on the left, similar to the "Devices" chart above it. I'm not totally sure this is a great idea, though, because it just moves the whitespace to the left. Thoughts welcome!
https://cloud.githubusercontent.com/assets/509309/13887316/0e88b2f6-ed09-11e5-8528-e35a7f4001c0.png

**Comment by hbillings** [comment]
(I also like the idea of breaking these charts down into "US" and "International" charts, with cities nested under "US" the way countries are currently nested under "International." That doesn't help with the whitespace issue, though.)

**Comment by gbinal** [comment]
I've added this to the backlog but am going to go ahead and close since we don't know when we'll be further refining the design.
