### ISSUE TITLE
Device stats under-representing Desktop numbers

### ISSUE THREAD

**Issue by reefdog** [18F/analytics.usa.gov#352]
Here's the data I'm seeing right now:

![analytics](https://cloud.githubusercontent.com/assets/4731/14716708/da3a467a-07b3-11e6-922c-a18b3cf1b3c9.png)

Desktop being <0.1% has to be wrong, especially combined with the OS stats.

**Comment by tdlowden** [comment]
Great catch. We're looking into it. Thanks for the heads up!

**Comment by cacraig** [comment]
Addressed by, https://github.com/18F/analytics-reporter/pull/154 .  Should be live shortly.

**Comment by konklone** [comment]
This fix is live on the site now. @reefdog want to give it a :eyes: ?

**Comment by reefdog** [comment]
Looks great! Thanks for the quick fix y'all!
