### ISSUE TITLE
The "Visits Today" graph is showing an hour or more behind current time

### ISSUE THREAD

**Issue by hamptonmf** [18F/analytics.usa.gov#353]
This was working over a week ago and now seems to be showing an hour behind for our main site and two hours for one of our agency sites. Can you point me in the right direction of where to look for the error in this?

Thanks,
Michael

**Comment by konklone** [comment]
Well, we have often observed the same thing -- and we have considered removing the graph from our site and the report from our systems. This is the only report that has a frequency of `realtime` but doesn't hit the Real Time API. I don't think you get a per-minute or per-every-two-minutes guarantee of freshness from Google's Core Reporting API.

It's probably the least information-dense and useful report in the system, so...

**Comment by hamptonmf** [comment]
Thanks. I've let our CIO know and we will probably end up removing it.
