### ISSUE TITLE
Mobile issues in header

### ISSUE THREAD

**Issue by tdlowden** [18F/analytics.usa.gov#357]
This using iPhone 6s iOS 9.3.1

![image1](https://cloud.githubusercontent.com/assets/6556888/14987935/a2f8f54c-111f-11e6-9228-41797b201881.PNG)

![image2](https://cloud.githubusercontent.com/assets/6556888/14987937/a5596ce0-111f-11e6-83f9-3e4b0ec010e3.PNG)

**Comment by hbillings** [comment]
This should be closed by the new design.
