### ISSUE TITLE
All font files 404ing on analytics.usa.gov

### ISSUE THREAD

**Issue by alex** [18F/analytics.usa.gov#358]
![screen shot 2016-05-08 at 9 50 09 pm](https://cloud.githubusercontent.com/assets/772/15101882/db5bc4a0-1566-11e6-9bb3-2ab02487d793.png)

**Comment by konklone** [comment]
Yes, it looks like this is the cause of some of the font issues we were observing -- we vendor'd only the CSS file from the USWD standards, and didn't vendor the fonts or images. Thanks for catching this, @alex.
