### ISSUE TITLE
Add more agencies

### ISSUE THREAD

**Issue by gbinal** [18F/analytics.usa.gov#365]
Add the rest of the CFO Act agencies:  
* Department of Agriculture
* Department of Defense
* Department of Health and Human Services
* Department of Housing and Urban Development
* Department of Homeland Security
* Department of Labor
* Department of State
* Department of Transportation
* Department of the Treasury
* Agency for International Development
* General Services Administration
* National Science Foundation
* United States Postal Service
* Nuclear Regulatory Commission
* Office of Personnel Management
* Social Security Administration

**Comment by gbinal** [comment]
Instructions for doing so are here - https://github.com/18F/analytics.usa.gov#adding-additional-agencies

**Comment by gbinal** [comment]
https://github.com/18F/analytics-reporter/pull/161 is moving this along.

**Comment by gbinal** [comment]
Note that we're holding on HHS for now.  We'll add it back in shortly.

**Comment by gbinal** [comment]
Okay - I'm reviewing these pages on staging.  Here's a first pass at issues I'm finding:  
* Department of Agriculture is not resolving
* USAID is showing EPA data 
* There's no data for USPS
* Department of Energy is showing v. low traffic (I think this is a known issue due to low implementation of DAP, right?)

**Comment by gbinal** [comment]
The USDA url is fixed by https://github.com/18F/analytics.usa.gov/pull/373

**Comment by gbinal** [comment]
The USAID data would be fixed by https://github.com/18F/analytics-reporter/pull/162

**Comment by gbinal** [comment]
I've confirmed that the Energy data is correct in proportion.

**Comment by gbinal** [comment]
OPM is missing - this fixes it - https://github.com/18F/analytics.usa.gov/pull/374

**Comment by tdlowden** [comment]
@gbinal I think we are good to close this issue, yes?

**Comment by gbinal** [comment]
Yep!
