### ISSUE TITLE
Reorder Dropdown order

### ISSUE THREAD

**Issue by gbinal** [18F/analytics.usa.gov#366]
It seems that the dropdown is ordered alphabetically by page filename ([here](https://github.com/18F/analytics.usa.gov/tree/adding-agencies/_agencies)).  We should change this so that it's in this order: 
* Department of Agriculture
* Department of Commerce
* Department of Defense
* Department of Education
* Department of Energy
* Department of Health and Human Services
* Department of Housing and Urban Development
* Department of Homeland Security
* Department of the Interior
* Department of Justice
* Department of Labor
* Department of State
* Department of Transportation
* Department of the Treasury
* Department of Veterans Affairs
* Agency for International Development
* Environmental Protection Agency
* General Services Administration
* National Aeronautics and Space Administration
* National Science Foundation
* Nuclear Regulatory Commission
* Office of Personnel Management
* Postal Service
* Small Business Administration
* Social Security Administration

**Comment by gbinal** [comment]
@cacraig - I see that you've got a PR in for it, but couldn't tell how it operated.  Is there a file to edit that changes the dropdown?

**Comment by konklone** [comment]
@gbinal The PR uses Jekyll's templating system to reorder the agency names during the rendering process, rather than editing a static file. So it should automatically handle all new added agencies going forward.

**Comment by cacraig** [comment]
Yep! No need to worry about it in the future, @gbinal

**Comment by gbinal** [comment]
Sorry for being dense, but I'm still struggling to grok it.  I guess I'm wondering where the order is determined or rather, if there was a desire to reorder it, where one could.

**Comment by cacraig** [comment]
@gbinal - 

`{% assign agencies = site.agencies | sort:"name"  %}`

This sets the variable agencies, which is sorted on the attribute "name".

If you wanted to change it to sort descending, you would do something like:
`{% assign agencies = site.agencies | sort:"name" | reverse  %}`

See: https://jekyllrb.com/docs/templates/

**Comment by konklone** [comment]
@gbinal In other words, there's no way in this implementation to tweak the ordering to make exceptions. It's fully alphabetical.

If you want to be able to tweak the order, then we can maintain the list manually, but that means always maintaining the list manually.

**Comment by gbinal** [comment]
Roger.  I'm cool with that.  The only change I'd have made is putting USAID after the Departments, but it's not worth more effort at this point.  

Thanks for resolving folks and sorry you had to walk me through it a bit.
