### ISSUE TITLE
Dropdown on /data pages missing arrow

### ISSUE THREAD

**Issue by tdlowden** [18F/analytics.usa.gov#379]
Possibly because it is the same white arrow from the homepage dropdown, but not on a white background?

![screen shot 2016-06-15 at 9 26 24 am](https://cloud.githubusercontent.com/assets/6556888/16081319/f5c8b960-32da-11e6-96da-5ac9ec205b92.png)

**Comment by gbinal** [comment]
Should be good now.  Good catch, though.  

![screen shot 2017-01-05 at 4 11 37 pm](https://cloud.githubusercontent.com/assets/633088/21697720/b23d33a6-d361-11e6-9347-f1d4447bf342.png)
