### ISSUE TITLE
Postal Service download links all dead

### ISSUE THREAD

**Issue by spikemc** [18F/analytics.usa.gov#384]
All download links on this page: https://analytics.usa.gov/postal-service/data/ appear to be dead and lead to a 404.

**Comment by gbinal** [comment]
Thanks, @spikemc!  

Confirmed.  The data urls all have /usps/ where /postal-service/ works.

**Comment by gbinal** [comment]
This should solve it - https://github.com/18F/analytics.usa.gov/pull/385

**Comment by konklone** [comment]
Fixed by #385.
