### ISSUE TITLE
Add a specific link to a JSON-page for the language code, as well, please.

### ISSUE THREAD

**Issue by wrhwebmaster** [18F/analytics.usa.gov#386]
Would you consider having tidbits in other JSON formats as well.

My interest is in the languages segment:
http://www.lingoes.net/en/translator/langcode.htm

A specific link to a JSON-page for the language code, 
could then be embedded as a 'web link' within:
https://analytics.usa.gov/data/live/language.json

**Comment by konklone** [comment]
Sorry, I don't quite understand what's missing -- does https://analytics.usa.gov/data/live/language.json not have what you're looking for?

**Comment by wrhwebmaster** [comment]
Example of what it does not have is:


what language do these examples

ar-ae   or   en-tt

represent?

If there is a separate JSON file,

we could use it to get a human readable language:

en-tt is short for English (Trinidad and Tobago)




On Tue, Jun 21, 2016 at 8:57 AM, Eric Mill <notifications@github.com> wrote:

> Sorry, I don't quite understand what's missing -- does
> https://analytics.usa.gov/data/live/language.json not have what you're
> looking for?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/18F/analytics.usa.gov/issues/386#issuecomment-227466697>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AExHhhGa-w-xXH1vp7rBoM7g5jXZi5K2ks5qN_vUgaJpZM4I60Zm>
> .
>



-- 
--
----------------------------------------------------------------------------
Western Region Webmaster
NWS Western Region Headquarters
Salt Lake City, UT
W-WRH.Webmaster@noaa.gov <W-wrh.Webmaster@noaa.gov>

​
[image: oneNWS_150x38.png] <http://www.wrh.noaa.gov/>   [image: Facebook
Channel] <https://www.facebook.com/NWSWestern>   [image: twitter32x32.png]
<https://www.twitter.com/NWSWestern>   [image: youtube32x32.jpg]
<https://www.youtube.com/NWSWRH>
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by divergentdave** [comment]
@wrhwebmaster Those codes are defined by a pair of ISO standards, there is a good overview of the subject here http://www.lunametrics.com/blog/2013/02/12/languages-report-google-analytics/

**Comment by konklone** [comment]
I think this is something we want to farm out to client users, for now, rather than maintain a hardcoded database of code->name mappings in the tool. Open to other ideas, and happy to re-open if there are other options!

**Comment by wrhwebmaster** [comment]
If you add ONE extra element, within that JSON file, would that be TOO MUCH
to ask?
Why are we commenting, then?


On Wed, Jun 22, 2016 at 8:53 AM, Eric Mill <notifications@github.com> wrote:

> I think this is something we want to farm out to client users, for now,
> rather than maintain a hardcoded database of code->name mappings in the
> tool. Open to other ideas, and happy to re-open if there are other options!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/18F/analytics.usa.gov/issues/386#issuecomment-227769726>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AExHhl5JD3cOZdFi9xWDaJufXqEHxG_Aks5qOUx1gaJpZM4I60Zm>
> .
>



-- 
--
----------------------------------------------------------------------------
Western Region Webmaster
NWS Western Region Headquarters
Salt Lake City, UT
W-WRH.Webmaster@noaa.gov <W-wrh.Webmaster@noaa.gov>

​
[image: oneNWS_150x38.png] <http://www.wrh.noaa.gov/>   [image: Facebook
Channel] <https://www.facebook.com/NWSWestern>   [image: twitter32x32.png]
<https://www.twitter.com/NWSWestern>   [image: youtube32x32.jpg]
<https://www.youtube.com/NWSWRH>
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by konklone** [comment]
@wrhwebmaster It's not the extra element, it's having to maintain a dataset inside the tool of language codes to language names. We recently expunged whitelists of browser/OS names and versions in order to avoid maintaining these lists (which were falling out of date).

Can you describe how likely this table of codes->names is to change? If it's very stable, that makes it easier.

**Comment by divergentdave** [comment]
One other thing to consider is the data quality of the language codes. Since the codes are reported by the browser, then passed through by Google Analytics and analytics.usa.gov, there will be a long tail of strings that aren't valid language codes. From the article I linked above, the problems can include underscores instead of hyphens, non-standardized two or three letter codes, hexadecimal garbage, blank entries, and even the letter "c".

I'd tend to agree that this cleanup and lookup work would best be left to the consumer. Depending on what you're doing, you could look up the top dozen or so from [here](https://en.m.wikipedia.org/wiki/List_of_ISO_639-1_codes) and [here](https://en.m.wikipedia.org/wiki/ISO_3166-1_alpha-2), or you could use something like [pycountry](https://pypi.python.org/pypi/pycountry/) for more comprehensive analysis.

**Comment by wrhwebmaster** [comment]
Here's a compromise.

Have a link in the page, that states 'where' to find the language codes.
Example-- if this is being used, then have it included 'someplace':
https://en.m.wikipedia.org/wiki/List_of_ISO_639-1_codes



On Wed, Jun 22, 2016 at 11:21 AM, David Cook <notifications@github.com>
wrote:

> One other thing to consider is the data quality of the language codes.
> Since the codes are reported by the browser, then passed through by Google
> Analytics and analytics.usa.gov, there will be a long tail of strings
> that aren't valid language codes. From the article I linked above, the
> problems can include underscores instead of hyphens, non-standardized two
> or three letter codes, hexadecimal garbage, blank entries, and even the
> letter "c".
>
> I'd tend to agree that this cleanup and lookup work would best be left to
> the consumer. Depending on what you're doing, you could look up the top
> dozen or so from here
> <https://en.m.wikipedia.org/wiki/List_of_ISO_639-1_codes> and here
> <https://en.m.wikipedia.org/wiki/ISO_3166-1_alpha-2>, or you could use
> something like pycountry <https://pypi.python.org/pypi/pycountry/> for
> more comprehensive analysis.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/18F/analytics.usa.gov/issues/386#issuecomment-227815451>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AExHhnl_Ydq-ZiWCenwz14Tgg6C1ss5Fks5qOW82gaJpZM4I60Zm>
> .
>



-- 
--
----------------------------------------------------------------------------
Western Region Webmaster
NWS Western Region Headquarters
Salt Lake City, UT
W-WRH.Webmaster@noaa.gov <W-wrh.Webmaster@noaa.gov>

​
[image: oneNWS_150x38.png] <http://www.wrh.noaa.gov/>   [image: Facebook
Channel] <https://www.facebook.com/NWSWestern>   [image: twitter32x32.png]
<https://www.twitter.com/NWSWestern>   [image: youtube32x32.jpg]
<https://www.youtube.com/NWSWRH>
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by konklone** [comment]
I think we should add descriptions for each of the datasets we publish, documenting what's in them, which will require some design work to accommodate. If/when we do that work to allow for documentation, we can definitely link to the ISO standards for country code and language code for this one.
