### ISSUE TITLE
Thresholds apply to data files by day

### ISSUE THREAD

**Issue by tdlowden** [18F/analytics.usa.gov#389]
Started with [this conversation](https://twitter.com/spikespike/status/753332101861236737).

The csv files for 90 day period break the data into daily rows, while the json for the same data aggregates for the entire 90 days. We're aware of that and fine with it. 

The interesting part is that the csv requires the data to meet the minimum threshold for _each day_ in order to create a row in the file, whereas since the json is aggregated, it only must meet the threshold as a total number of sessions across the 90 days.

Example: in screen sizes report for USPS data, 480x854 only appears 9 days of the 90 in the csv report, because the other 81 days, that resolution failed to exceed 5000 sessions.

**Comment by tdlowden** [comment]
As noted by @konklone, the above is not actually the case. the json and the csv do line up, because the json is aggregating only what exists in the csv. therefore, we've discovered that the threshold is not being applied across the entire 90-day set of data, but instead on each day, only to be aggregated in the json.

I believe we set the threshold at >5000 assuming that meant over the 90-day period. As such, we may want to drastically decrease the threshold, since it is apparent that it must be achieved daily to constitute inclusion in the data files.

**Comment by tdlowden** [comment]
this also warrants examining the other files/thresholds.

**Comment by tdlowden** [comment]
Suggested changes in this doc:

https://docs.google.com/spreadsheets/d/1UEfDyUUAbuEvOS6cufvaYShGsOCO-BfrQpt33wOGmDQ/edit#gid=0

**Comment by jmhooper** [comment]
@tdlowden: This list mentions "City" report. Our current report for that is realtime and doesn't have a threshold. Do we want to add a threshold to the realtime query?

**Comment by jmhooper** [comment]
Yep 💯
