### ISSUE TITLE
data and totals values are not appearing in generated realtime report

### ISSUE THREAD

**Issue by jmolayem** [18F/analytics.usa.gov#394]
for some reason data is not showing up in every realtime report that I generated. Have you encountered this?

  },
  "data": [],
  "totals": {}
}

**Comment by jmolayem** [comment]
Would I need to actively enable "real time" in the analytics account? I thought this was a default.

**Comment by jmolayem** [comment]
this may help explain it better: http://analyticsdash-jm.s3.amazonaws.com/cd10/index.html

If you see in console, Uncaught TypeError: Cannot read property 'active_visitors' of undefined. However, in network tab, you can see all the correct .json files have been received.

**Comment by jmolayem** [comment]
strange...http://analyticsdash-jm.s3.amazonaws.com/geohub/index.html works. 
http://analyticsdash-jm.s3.amazonaws.com/opendata/index.html works. but for some reason the other ones aren't working. I'm 99% something's up on the Google Analytics end.

**Comment by konklone** [comment]
I'm having trouble following, @jmolayem, but I think this is an issue with your Google Analytics account. If you find a bug in `analytics-reporter`, please report it [to the analytics-reporter repo](https://github.com/18f/analytics-reporter/issues). (This is the repo specific to the front-end.)
