### ISSUE TITLE
New datasource suggestion: more dimensions / breakdowns

### ISSUE THREAD

**Issue by ggrigo** [18F/analytics.usa.gov#396]
This is an awesome initiative! Thanks

However, proper data analysis requires the availability of more dimensions within the same row. This enables breakdown analysis.

I suggest the creation of a new, daily, dataset that has the following dimensions:

[day] : [website] : [country] : [source] : [device] : [page]

Interesting metrics would be: 
--visits, 
--pageviews, 
--users, 
--entries, 
--bounces
--avg. (or total) time spent

Or anything towards this direction, in case the above proves to be too big of a dataset. Then again, this is where value-add analysis happens :)

**Comment by tdlowden** [comment]
Thanks for the suggestion @ggrigo! We're assessing adding new datapoints now, and hope to have them implemented in the coming months.
