### ISSUE TITLE
Links for Top Pages not working

### ISSUE THREAD

**Issue by jmolayem** [18F/analytics.usa.gov#402]
Hi,
We just launched the City of Los Angeles' version of this page. 

Our links for the "top pages" are not working. I'm trying to troubleshoot this. I've confirmed that they don't work in development either. Do you know if there is any custom configuration required for this?

**Comment by allejo** [comment]
Are the links being displayed relative? (i.e. without a domain) Have you tried making use of [`ANALYTICS_HOSTNAME`](https://github.com/18F/analytics-reporter#other-configuration) when you're running analytics-reporter?

**Comment by jmolayem** [comment]
Thanks. I did make use of analytics_hostname. 

Here is an example for www.lacity.org:

# bigla analytics page

export ANALYTICS_REPORT_IDS="ga:xxxxxxx"
export AWS_BUCKET_PATH=data
export ANALYTICS_HOSTNAME=www.lacity.org

What's interesting is it's forwarding to the relative path example: "find-jobs/", but, it's not appending to "www.lacity.org"

**Comment by jmolayem** [comment]
I moved this **export ANALYTICS_HOSTNAME=www.lacity.org** from the "envs" folder to the shell file thinking it may help. It still is an issue. We are also monitoring sites that don't have "www.lacity.org" as the hostname so that could be causing it.

**Comment by jmolayem** [comment]
My apologies. I forgot to include our site: http://webanalytics.lacity.org/

**Comment by allejo** [comment]
A more robust solution may be in store from 18F but what we did to fix this on our instance was change [line 333 of `js/index.js`](https://github.com/18F/analytics.usa.gov/blob/9ff5c1300e29031bb66f1ac451e58afb39e0b60e/js/index.js#L333) to the following:

```js
return exceptions[d.page] || ("http://" + d.domain + d.page);
```

Though this change doesn't take into account if the `d.domain` exists or not. If you're using `ANALYTICS_HOSTNAME`, it'll exist.

**Comment by jmolayem** [comment]
Thanks. That change looked like it work. However, the link is redirecting to:

`http://https//lacity.org/find-jobs`

**Comment by jmolayem** [comment]
Resolved.
I changed:
`return exceptions[d.page] || ("http://" + d.domain + d.page);`
to
`return exceptions[d.page] || (d.domain + d.page);`

Thank you for the help!

**Comment by allejo** [comment]
As a note to anyone else who many have this issue, `d.domain` in the above discussion is the value that comes from `ANALYTICS_HOSTNAME`. So the prepending of the "http://" depends entirely on whether or not `ANALYTICS_HOSTNAME` has it.

**Comment by konklone** [comment]
I just want to ring in and say thanks to @allejo from Santa Monica for helping so quickly and effectively! 😺 This is model open source community stuff right here.
