### ISSUE TITLE
Set up Travis-CI and add badge

### ISSUE THREAD

**Issue by gbinal** [18F/analytics.usa.gov#415]
https://travis-ci.org/18F/analytics.usa.gov

**Comment by gbinal** [comment]
done

**Comment by gbinal** [comment]
I was mistaken.  The `.travis.yml` file still needs correcting.

**Comment by jmhooper** [comment]
Okay, a few options we have for what we can do with Travis:

__analytics.usa.gov__

- [ ] Verify that build works
- [ ] Deploy to production when changes are made to master

__analytics-reporter__

- [ ] Run a test suite (this requires setting up a test suite)
- [ ] Deploy to production when change are made to master (this will require better secret key management; described partially in #172)

**Comment by jmhooper** [comment]
Travis is setup for `analytics.usa.gov`, but setting up Travis for `analytics-reporter` is going to have to wait for:

- 18f/analytics-reporter#183 before we can do continuous deployment
- Us to have a test suite before we can run tests in CI

**Comment by gbinal** [comment]
I'm going to go ahead and close this.
