### ISSUE TITLE
Bump up our Code Climate score

### ISSUE THREAD

**Issue by gbinal** [18F/analytics.usa.gov#417]
Pulse is currently at a 0.63 [on Code Climate](https://codeclimate.com/github/18F/analytics.usa.gov).  We should do a pass through the [C](https://codeclimate.com/github/18F/analytics.usa.gov/code?q=rating%3AC), [D](https://codeclimate.com/github/18F/analytics.usa.gov/code?q=rating%3AD), and [F](https://codeclimate.com/github/18F/analytics.usa.gov/code?q=rating%3AF) factors to try and address any low hanging fruit.

**Comment by gbinal** [comment]
Note that we should consider implementing a .codeclimate.yml file that removes irrelevant controls, a la https://github.com/18F/pulse/blob/master/.codeclimate.yml.

**Comment by jmhooper** [comment]
Worth noting that Code Climate currently thinks our default branch is `18f-pages`. We're on the OSS plan which means in order to fix it we'll need to email Code Climate support asking to change it.

**Comment by gbinal** [comment]
This is better.  I think we can close this.
