### ISSUE TITLE
Agency selector errors if "data" is in the agency html filename

### ISSUE THREAD

**Issue by shua123** [18F/analytics.usa.gov#420]
Creating an agency page with "data" in the filename breaks the agency selector drop down. In our case I created an agency page named "opendataportal.html" (https://github.com/CookCountyGov/analytics/issues/2). 

I believe the issue is with the line `{% unless page.url contains 'data' %}` in default.html https://github.com/18F/analytics.usa.gov/blob/master/_layouts/default.html#L25 which I think is really meant to filter /data/ pages.

![image](https://cloud.githubusercontent.com/assets/1593537/21441506/e6203c5e-c85d-11e6-8758-7e36207b83e3.png)

**Comment by konklone** [comment]
That sounds like the right diagnosis of the issue. I suppose we could change it to `/data/`, as long as we know there's a trailing slash in that variable, or `/data` if we don't. Liquid templates are more restrictive in the kind of matching you can do than straight Ruby.

Either way, this is definitely a bit of a hack. Any other thoughts?

**Comment by tdlowden** [comment]
@konklone, is it your opinion we should make the change to /data?

**Comment by konklone** [comment]
I'd like another dev to give it a quick look and see if there are any non-hack options in Jekyll to do this right, but if I had to pick a route, yes.

**Comment by tdlowden** [comment]
I see that this was fixed for the Cook County site, and being that this is a fix that is specific to forked dashboards, I'm going to close for now. If this is a persistent issue, we can make the change.
