### ISSUE TITLE
Weigh refactoring the cloud.gov work to decrease technical debt

### ISSUE THREAD

**Issue by gbinal** [18F/analytics.usa.gov#423]

**Comment by konklone** [comment]
https://github.com/18F/analytics-reporter/issues/172#issuecomment-261755583

**Comment by konklone** [comment]
move the environment variables into a user-provided service: https://docs.cloudfoundry.org/devguide/services/user-provided.html

**Comment by gbinal** [comment]
@jmhooper's done a lot with this, so I'm going to go ahead and close.
