### ISSUE TITLE
time series stats

### ISSUE THREAD

**Issue by pete-rjames** [18F/analytics.usa.gov#424]
Just wondering if there are any plans to provide stats grouped by day/month so users can look at trends and seasonality?

**Comment by gbinal** [comment]
Yep!  We're working on an API to provide historical data going forward.  If you keep an eye on https://github.com/18F/analytics-reporter/issues/194, we'll be sure to keep providing updates.

**Comment by pete-rjames** [comment]
That sounds great - thanks.
