### ISSUE TITLE
create network diagram

### ISSUE THREAD

**Issue by gbinal** [18F/analytics.usa.gov#429]

**Comment by gbinal** [comment]
![img_20170216_121251](https://cloud.githubusercontent.com/assets/633088/23032162/94d939f8-f441-11e6-8569-31df5aa41480.jpg)

**Comment by jmhooper** [comment]
This diagram does not include the reporter.

**Comment by gbinal** [comment]
Unfortunately, someone missed the 'please don't erase until March 1' sign next to this, so I'm going to need to redo it at some point.  

I'll then try to also include: 
* app - 
* site - 
* staging site - 
* analytics reporter - is running as a cloud.gov app in govcloud

**Comment by gbinal** [comment]
done
