### ISSUE TITLE
Remediate and document the scan results

### ISSUE THREAD

**Issue by gbinal** [18F/analytics.usa.gov#430]
* https://compliance-viewer.18f.gov/results/dap/current

**Comment by gbinal** [comment]
* The first error in ^^^ is not an issue.  
* @jmhooper - game to take a look at the second issue `Incomplete or No Cache-control and Pragma HTTP Header Set` and either address it or confirm that we should ignore.

**Comment by jmhooper** [comment]
I added the headers that will make compliance viewer happy, but I have some concerns about disabling caching all together since some of our content is public, static content which should be able to be safely cached.

**Comment by jmhooper** [comment]
closed by #440
