### ISSUE TITLE
Revisit real-time call length

### ISSUE THREAD

**Issue by tdlowden** [18F/analytics.usa.gov#432]
We're currently calling the realtime data once per 10 minutes, which was done to accommodate the API max while 2 parallel instances of the site were running during cloud transition. We should:

* make sure the second, not-in-use instance is killed
* assess a good time period to call the realtime data (I suggest 5 min)
* adjust the documentation on the site (/data pages) to reflect the new "update" time for the realtime files

**Comment by jmhooper** [comment]
I've open 18F/analytics-reporter#184 to address this on the reporter side, but I can't seem to find any docs on the `/data/*` pages to update.

**Comment by jmhooper** [comment]
The change on the data page is to the update frequency column here:

![image](https://cloud.githubusercontent.com/assets/963654/22125998/954cf5e2-de5b-11e6-9745-7127735e3248.png)

**Comment by jmhooper** [comment]
The update frequency on the data pages pictured above was updated here: https://github.com/18F/analytics.usa.gov/commit/078e098f7b77d1ef2281b434101b89010d579297
