### ISSUE TITLE
ensure new relic sends to a helpful email addresses

### ISSUE THREAD

**Issue by gbinal** [18F/analytics.usa.gov#442]

**Comment by tdlowden** [comment]
@jmhooper had a great idea to instead have newrelic and github integrate into a common Slack channel. I think this is the way to go. As for an email address as a backup, we can use something that is used for this purpose only.

**Comment by gbinal** [comment]
Roger.  FWIW, we have analytics.usa.gov@gsa.gov now, which I'd suggest sending to instead of dap@ in the future.  

Otherwise, I'll go ahead and close this.
