### ISSUE TITLE
Offer a short writeup of remaining code climate issues

### ISSUE THREAD

**Issue by gbinal** [18F/analytics.usa.gov#445]
In the [Documentation for False Positives for analytics.usa.gov](https://docs.google.com/document/d/12eOpHtCHw5VilHPotVN_4X_CuNpJ7zqOJQ2DzfAvH20/edit#heading=h.meucamy832pt), there's a section for the Code Climate results.  

@jmhooper - can you offer a 1-3 sentence summary of the remaining issues that remain in our code climate results?  It doesn't need to be anything fancy, just a general overview.  

If it's helpful, check out the [same section](https://docs.google.com/document/d/1pRpb48GT1UyZpKKJlLRD4Oj2oaKMobXukzwby8ntZno/edit#heading=h.3pouwmz2h3e6) for pulse.cio.gov.

**Comment by jmhooper** [comment]
The issues that Code Climate found were either opinionated style issues or issues with similar code. The process for fixing those should involve fixing those issues as we find a need to update that code, rather than changing the codebase for style's sake which risks introducing regressions.

**Comment by gbinal** [comment]
Looks good.  Thank you.
