### ISSUE TITLE
Add real-time threshold language to agency pages

### ISSUE THREAD

**Issue by tdlowden** [18F/analytics.usa.gov#446]
Current homepage describes that real-time only includes pages with 10 or more visitors. We should extend this to agency pages.

![screen shot 2017-02-28 at 4 30 43 pm](https://cloud.githubusercontent.com/assets/6556888/23464466/15b4a398-fe63-11e6-9027-b49805d9026e.png)

**Comment by gbinal** [comment]
Closing this in favor of a PR that fixes it - https://github.com/18F/analytics.usa.gov/pull/471
