### ISSUE TITLE
sec.gov traffic data volume is skewed by 404 replies to HEAD requests

### ISSUE THREAD

**Issue by Aditza2015** [18F/analytics.usa.gov#447]
Hello,
i posted this issue yesterday: https://github.com/18F/SEC.gov-developer/issues/67

i think i should post a follow-up/pointer to it here too because this problem has the potential to cause an artificial HUGE increase in the volume of the data traffic reported by sec.gov

Since the FTP access to EDGAR has been shut down permanently at the end of December 2016 all downloads of SEC filings from EDGAR must be done via HTTPS now.

However, the broken support for HTTP HEAD requests means that the traffic volume numbers are multiplied, sometimes even exponentially, because this happens:

**1).** client app downloads initially some files (GET requests) from sec.gov EDGAR archive - usually the XML sitemap index files. (let's say the data volume of this download is about 5 gigabytes)

**2).** wait random interval x

**3).** client app checks if any of the files it downloaded at step 1 have been changed on server (HEAD requests) but instead it receives replies that the files have been deleted from server (the server sends a `404 Not Found` reply instead of proper data) so the client app deletes the local cached copy.

**4).** wait another random interval y

**5).** client app tries again to download the files they are interested in, but since the server said that the files have been deleted, the client app has already deleted the local cache at step 3 and now it ends up finding again and downloading ALL the files (another set of GET requests)
(let's say the data volume of this download is about 5.01 gigabytes)

where:
- the x interval can be anything from 10-15 minutes to 10 weeks or more
- the y interval can be anything from 10 seconds to 10 weeks or more (but usually tends towards the 'seconds' side because the missing cached files deleted at step 3 will trigger a quick progression to step 5)

What would have been a mere 10-50 megabyte download at step 5 (including changed files) is now all of a sudden a full new download of 5 gigabytes of data plus the new data.

On the old FTP system it was possible to query the timestamp / size of a sitemap index XML file from EDGAR without downloading it, but since the transition to HTTPS-only this is no longer possible directly.

This will screw up the traffic volume statistics for sec.gov because the site is forcing client apps to re-download (GET) all the (index) data files instead of just letting them check (HEAD) if the files have been changed.

**Comment by konklone** [comment]
@Aditza2015 I don't know whether the SEC's own analytics collection includes arbitrary traffic hits, but the data that shows up on analytics.usa.gov will only occur for data sent to Google Analytics. HEAD requests won't do that, because the server isn't returning JavaScript and the client wouldn't execute it even if they did. So, the data you see on analytics.usa.gov should be unaffected by the issue you describe.
