### ISSUE TITLE
Different results at analytics.usa.gov/data for a domain when I generate CSV for all domains versus restrict to a department

### ISSUE THREAD

**Issue by vipulnaik** [18F/analytics.usa.gov#451]
To reproduce, compare:

https://analytics.usa.gov/data/live/all-domains-30-days.csv (obtained by clicking on the first CSV "Visits to all domains over 30 days" with menu selection "All Participating Websites")
against

https://analytics.usa.gov/data/treasury/all-domains-30-days.csv (obtained by clicking on the first CSV "Visits to all domains over 30 days" with menu selection "Department of the Treasury")

Look for the line beginning with irs.gov in both. The numbers are very different for the two.

At the time I downloaded both files (around 02:00 UTC on Sunday, March 26, 2017), the lines for irs.gov were as follows.

Column headers:

domain,visits,pageviews,users,pageviews_per_session,avg_session_duration,exits

values in https://analytics.usa.gov/data/live/all-domains-30-days.csv :

irs.gov,89061783,207198106,35811578,2.326453603561923,117.51957891972587,89355228

values in https://analytics.usa.gov/data/treasury/all-domains-30-days.csv :

irs.gov,127842160,279274537,45569417,2.184526114076921,106.5164065516415,128049659

I'm also attaching the two files at the time of download.
[download of https://analytics.usa.gov/data/live/all-domains-30-days.csv](https://github.com/18F/analytics.usa.gov/files/870508/live.txt)
[download of https://analytics.usa.gov/data/treasury/all-domains-30-days.csv
](https://github.com/18F/analytics.usa.gov/files/870507/treasury.txt)

**Comment by tdlowden** [comment]
I can replicate this by downloading the CSVs from /data and /treasury/data, but I checked in the actual GA interface, and I'm getting identical numbers. The delta is large enough that I don't think it is a sampling issue with the API, so I believe it is something with the creation of the reports themselves. We're looking into this, thanks for flagging!

**Comment by gbinal** [comment]
@tdlowden - I don't think it's related but one thing to look at is the query parameters for that report - https://github.com/18F/analytics-reporter/blob/master/reports/usa.json#L481-L491.

**Comment by laurenancona** [comment]
I'll need to revisit some documentation with a fresh brain tomorrow, but I think the issue might be related to the way Google stores session data. While not technically "sampling" in the way we usually mean in this context, some of the core metrics are effectively extrapolated from aggregated metrics, which is an efficiency on their end. I know I'm not explaining this well; I'll loop back in the morning.

**Comment by vipulnaik** [comment]
@laurenancona I'm following up.

If it's confirmed that this is an issue on Google's end due to subsampling or approximation, which of the two lists is the more accurate? Would it be possible or desirable to make queries for the more accurate version and power both views with those queries (so that people get consistent and more accurate data)?

**Comment by tdlowden** [comment]
@vipulnaik we figured it out and just merged a fix:

https://github.com/18F/analytics-reporter/pull/232

**Comment by vipulnaik** [comment]
Thanks! I'll close this issue then.

**Comment by vipulnaik** [comment]
Although the numbers don't exactly match when I do the steps outlined in the issue, they are within 5% of each other, which is explainable by subsampling errors, different time intervals for refresh, etc.
