### ISSUE TITLE
Create a vanilla api page 

### ISSUE THREAD

**Issue by gbinal** [18F/analytics.usa.gov#455]
@jmhooper - Can you create a blank content page at analytics.usa.gov/developer so that I can take a first pass at API documentation?

**Comment by jmhooper** [comment]
Should I use the staging API URL for this page, or something different?

**Comment by gbinal** [comment]
That's fine!

**Comment by gbinal** [comment]
Done - thanks, @jmhooper!  

https://analytics.usa.gov/developer
