### ISSUE TITLE
Update Dockerfile.production to include nginx.conf

### ISSUE THREAD

**Issue by jmhooper** [18F/analytics.usa.gov#465]
We have a custom nginx configuration in our repository, but the production Docker image does not use that configuration. We fix that. 2 steps:

- Make nginx configuration use env vars for things like S3 url and generate it with erb to during docker build
- Change production image build to use the generated nginx configuration

**Comment by gbinal** [comment]
@jmhooper - just to check, did #469 complete this or should we leave it open?

**Comment by jmhooper** [comment]
@gbinal: This is done 👍
