### ISSUE TITLE
Add documentation for onboarding / offboarding developers

### ISSUE THREAD

**Issue by jmhooper** [18F/analytics.usa.gov#485]
We need to create documentation describing the process for onboarding and offboarding users to reference from within our SSP. This should mention all the places members need to be granted or revoked access.

Additionally, these docs should describe a process for opening issues to track the onboarding / offboarding of a particular user.

**Comment by jmhooper** [comment]
See control AC-2 part F

**Comment by gbinal** [comment]
Thanks!  Done - https://github.com/18F/analytics.usa.gov/blob/master/docs/procedures.md
