### ISSUE TITLE
Ensure workflows are documented for the team 

### ISSUE THREAD

**Issue by gbinal** [18F/analytics.usa.gov#487]
_This is a running checklist of processes that we should make sure we can do without @jmhooper._

* [x] Restart the cloud.gov app 
* [x] Check the logs for the cloud.gov app
* [x] Manage user access to the cloud.gov app 
* [ ] Tweak the New Relic settings 
* [x] Check the analytics.usa.gov api analytics 
* [x] Manage the analytics.usa.gov api analytics 
* [ ] Check GA Developer Key Usage
* [ ] Manage GA Access

**Comment by levinmr** [comment]
Closing stale issue.
