### ISSUE TITLE
Analytics on screen resolution of users

### ISSUE THREAD

**Issue by natep77** [18F/analytics.usa.gov#494]
I work for a government e-learning contractor and would love to get analytics on screen resolution for government employees e-learning courses. Right now we are still suggested 1024x768 most of the time, but I believe those specs are no longer up-to-date for the current web.

**Comment by konklone** [comment]
Hi @natep77, we actually publish data on this:

https://analytics.usa.gov/data/

There's a `Screen sizes` report in CSV and JSON. It's broken out widely -- so you'll get how many people used a particular screen resolution on each particular day, over a 90-day window. The file is updated in place each day, reflecting a rolling window of the previous 90-days.

So you may have to do a little bit of Excel/other work to sum up the data the way you want it, and you may also want to collapse some similar resolutions into each other (or identical resolutions where the width and height are just flipped), but the raw data is there.
