### ISSUE TITLE
Puerto Rico is part of the United States

### ISSUE THREAD

**Issue by jgsmith-usds** [18F/analytics.usa.gov#496]
Rather than list Puerto Rico under the list of International locations from which a visitor can visit a website, it should be listed under the United States since it is part of the US.

Noticed it on https://analytics.usa.gov/small-business-administration/

**Comment by tdlowden** [comment]
I have noticed this as well @jgsmith-usds, thanks for pointing it out. The reason this happens is that Google Analytics classifies Puerto Rico separately from `United States` in its platform, which then gets passed on to analytics.usa.gov.  While I agree that it is a questionable classification, it does follow a pattern that Google Analytics has established for territories of countries, even beyond the US. For example, along with Puerto Rico, Guam, and US Virgin Islands being listed separately, GA also has the Faroe Islands (Denmark), Christmas Island (Australia), Bermuda (UK), and many other territories/divisions of a country listed as their own unique entity in the `country` dimension.

**Comment by tdlowden** [comment]
Doing some research, I see that the official dimension name used to be `Country/Territory` before apparently Google shortened it to just `Country`.

**Comment by Rio517** [comment]
I just clicked to this repo to raise this issue as well. 

Instead of adding the data to the US, would it be possible to add as a subheading under US - similarly to the way you have different countries under "International" now.  

At a minimum, perhaps you could append an asterisk to PR and other U.S. territories and explain why it is under "International" and not the US?

Thanks, 

-Mario

**Comment by tdlowden** [comment]
After seeing this issue raised again on Twitter, I wonder if an appropriate, but easy thing to do would be to change the header from "International" to "Other Countries and Territories". thoughts @jmhooper and @konklone ?

**Comment by laurenancona** [comment]
Agree that that’s probably the most expedient way to better account for this, for now. 

This could arguably be addressed in a more complete way by modding the report configuration in `analytics-reporter`

**Comment by tdlowden** [comment]
https://github.com/18F/analytics.usa.gov/pull/505

**Comment by tdlowden** [comment]
It's not perfect, but until we can find a long term solution, we've at least done this:

![screen shot 2018-04-05 at 1 14 39 pm](https://user-images.githubusercontent.com/6556888/38381078-aebb38c6-38d3-11e8-8b36-dd0439c8ab68.png)

Going to close this issue, but know that you've been heard, and in our next cycle of work on the site (which is irregular at this point), we'll try to address it thoughtfully! Appreciate everyone's comments.
