### ISSUE TITLE
City-level data?

### ISSUE THREAD

**Issue by alainawiens** [18F/analytics.usa.gov#497]
Is there way to scale the data in the dashboard down to the city level, specifically for Flint, Michigan?

**Comment by ErieMeyer** [comment]
Great question! cc @gbinal

**Comment by tdlowden** [comment]
Hi @alainawiens! I think I might need some elaboration on this. You are looking for where people in Flint are visiting on federal gov websites? @gbinal told me he invited you to our Slack public channel. Care to go there and we can discuss a bit?

**Comment by alainawiens** [comment]
Thanks for the quick reply @tdlowden! I'm working on joining the channel now, and I'm more than happy to discuss where it makes the most sense.
