### ISSUE TITLE
New System Owner Permissions

### ISSUE THREAD

**Issue by tdlowden** [18F/analytics.usa.gov#499]
@gbinal As per https://github.com/18F/analytics.usa.gov/blob/master/docs/procedures.md, I request an update to any relevant permissions on cloud.gov and/or Github, NewRelic, and any other systems pertinent to analytics.usa.gov to reflect me as the system owner.

**Comment by gbinal** [comment]
Definitely - sounds great.  

Here's a checklist to track progress: 
* [x] Cloud.gov 
* [x] GitHub (3 repos) 
* [ ] New Relic
* [ ] Circle CI, Code Climate, Gemnasium 
* [ ] AWS?

**Comment by gbinal** [comment]
For AWS, that's within cloud.gov and I don't think there's really any need for you to set up credentials.  

For New Relic, Circle CI, Code Climate, Gemnasium - it'd be good to do a quick 30 minutes with @jmhooper to make sure that's handed off well and he doesn't feel like there's any loose ends there.

**Comment by tdlowden** [comment]
Thanks! @jmhooper, can we schedule some time next week?

**Comment by jmhooper** [comment]
Yep, definitely
