### ISSUE TITLE
Visitors Today Graph Missing Data

### ISSUE THREAD

**Issue by stphnwlkr** [18F/analytics.usa.gov#502]
Agencies after DHS in the dropdown have nothing but 0 values for visits in the today.json file.

**Comment by tdlowden** [comment]
thanks for flagging this @stphnwlkr. we're looking into it now.

**Comment by tdlowden** [comment]
We found and fixed issue with our restarter. Looks like things are running as expected today! Thanks @stphnwlkr; moving to close this issue.

**Comment by stphnwlkr** [comment]
Working as expected. Thank you.
