### ISSUE TITLE
Allow selecting any of the 400 participating domains

### ISSUE THREAD

**Issue by anselmbradford** [18F/analytics.usa.gov#508]
Unless I'm missing it, it's not possible to view all participating domains individual outside of those listed [here](https://github.com/18F/analytics.usa.gov/tree/master/_agencies). Instead of a drop-down, could you use search with a type-a-head to allow accessing all domains?

**Comment by tdlowden** [comment]
Hey Anselm!

At this time, it's limited to what's available. I recognize that the API is currently offered in a limited fashion, but we aren't in a development cycle at the moment, so there won't be any immediate changes. I will keep this suggestion in mind for our next development sprints on the site, though! Apologies we can't make more immediate changes.
