### ISSUE TITLE
Change color on Agency dropdown

### ISSUE THREAD

**Issue by tdlowden** [18F/analytics.usa.gov#518]
As per a UX test, users sometimes didn't realize that the agency dropdown was in fact a dropdown. Changing it from the dark blue to the lighter blue (HEX #2b75b9) in the style should help it contrast. Hopefully we can test this again later to prove it out.

**Comment by lauraGgit** [comment]
## Sample with the blue:
![image](https://user-images.githubusercontent.com/5840989/48510519-15f96c80-e822-11e8-876c-f32f42014347.png)

## Sample with white background:
![image](https://user-images.githubusercontent.com/5840989/48510647-7c7e8a80-e822-11e8-87ca-ade82c55613c.png)

**Comment by tdlowden** [comment]
Let's try the blue, and if needed I can attempt a longer A/B test between the colors in the future.
