### ISSUE TITLE
Make reporting an issue more prominent

### ISSUE THREAD

**Issue by tdlowden** [18F/analytics.usa.gov#519]
users in a UX test had trouble finding how to report an issue when the link was buried in a sentence. Making reporting an issue more prominent and stand-alone should help alleviate this.

**Comment by lauraGgit** [comment]
This is the sentence that you're currently referring to? "We plan to expand the data made available here. If you have any suggestions, or spot any issues or bugs, please open an issue on GitHub or contact the Digital Analytics Program."

**Comment by tdlowden** [comment]
Correct. Any thought on how to make `Open an issue` a more prominent feature?

**Comment by lauraGgit** [comment]
Calc/ Login, use a footer break to make some of that more prominent, which may be a way for us to address that. I can mock something up, if its useful.
![image](https://user-images.githubusercontent.com/5840989/48511866-f6644300-e825-11e8-9fdc-cec014f26892.png)

![image](https://user-images.githubusercontent.com/5840989/48511885-02e89b80-e826-11e8-9546-a84cbea62916.png)

**Comment by lauraGgit** [comment]
and Federalist:
![image](https://user-images.githubusercontent.com/5840989/48511969-37f4ee00-e826-11e8-8409-bde187d4ded4.png)

**Comment by tdlowden** [comment]
that's a great idea. moving some of those important links into a footer would be a good move

mainly: `Email us` and `Report an issue`

**Comment by tdlowden** [comment]
Maybe even all the links in the highlighted:
![screen shot 2018-11-14 at 4 02 36 pm](https://user-images.githubusercontent.com/6556888/48512150-c49fac00-e826-11e8-9c24-31bc497fe5f4.png)

**Comment by lauraGgit** [comment]
yes, i'll mock up a more visual footer and post a screen shot!

**Comment by lauraGgit** [comment]
Ok, @tdlowden here is a first take:
![image](https://user-images.githubusercontent.com/5840989/48515322-68d92100-e82e-11e8-9250-5f10f4f637f6.png)

**Comment by tdlowden** [comment]
omg this looks great!
