### ISSUE TITLE
As a user, I want something useful out of that hourly bar chart

### ISSUE THREAD

**Issue by tdlowden** [18F/analytics.usa.gov#524]
Our colleague David K had a great idea to run an annual daily average of hourly traffic and create a permanent line across the hourly bar chart, to display if any particular day or hour is trending with more or less traffic than the norm. I can run reports across a year by hour and find out the averages for each hourly increment by weekday.

We'd need this line to change each day, since weekend visits and certain weekdays trend higher/lower than others.

**Comment by levinmr** [comment]
Closing stale issue
