### ISSUE TITLE
As an API user, I would like to filter the API response by domain

### ISSUE THREAD

**Issue by tdlowden** [18F/analytics.usa.gov#536]
## What kind of issue?
- [x] Feature Request?
- [ ] Bug

## User story
As an API user, it would be beneficial for me to be able to filter responses by the specific site or sites I work on, and not have to get a large response and filter it afterward.

## Acceptance Criteria
- [ ] See an API response with only the specified domains that I have queried for

**Comment by lauraGgit** [comment]
by which ones its possible for

**Comment by tdlowden** [comment]
this was completed by @lauraGgit! moving to close
