### ISSUE TITLE
As an API user, I would like to filter responses by date

### ISSUE THREAD

**Issue by tdlowden** [18F/analytics.usa.gov#537]
## What kind of issue?
- [x] Feature Request?
- [ ] Bug

## User story
As an API user, it would be helpful for me to query for a specific time period of data.

## Acceptance Criteria
- [ ] I can include a `before` parameter and any data before that date will be included in a response (up until the historical start date)
- [ ] I can include an `after` parameter and any data after that date will be included in a response (up until yesterday)
- [ ] I can include both `before` and `after` and any data returned will be within the timeframe, in order to search within a specified time period.

**Comment by lauraGgit** [comment]
Exclusive query.

**Comment by tdlowden** [comment]
closing!
