### ISSUE TITLE
Upgrade to jquery v3.0.0 or higher

### ISSUE THREAD

**Issue by tdlowden** [18F/analytics.usa.gov#550]
## What kind of issue?
- [x] Feature Request?
- [ ] Bug

## User story
*Please provide us with a description of the issue as a user story*
According to GSA IT, we must upgrade to jquery 3.0.0 or higher.

## Acceptance Criteria
- [ ] jquery version is 3.0.0 or higher

**Comment by tdlowden** [comment]
@lauraGgit or @jmhooper, is this something I could ask a small amount of your time to look into?

**Comment by ryanwoldatwork** [comment]
@tdlowden - I don't see jQuery in this repo.

Is this still valid?

**Comment by ryanwoldatwork** [comment]
I don't see jQuery in this repo.

Closing.
