### ISSUE TITLE
API docs need more "back to top" links

### ISSUE THREAD

**Issue by Ryandaydev** [18F/analytics.usa.gov#555]
## What kind of issue?
- [ ] Feature Request?

## User story
As an API user, I would like to have more "back to top" links in the [API documentation](https://open.gsa.gov/api/dap), so that I can get back to the top more easily after viewing a section.

## Acceptance Criteria
- [ ] Every section in the nav bar has a "back to top" link at the bottom

**Comment by Ryandaydev** [comment]
@gbinal You may want to take a look at this one.

**Comment by ctrimm** [comment]
Filled this as an issue in the appropriate repository, I believe that we can close this issue out.
