### ISSUE TITLE
Please add a website status update (up/down)...at least for SAM.gov

### ISSUE THREAD

**Issue by philadopolis** [18F/analytics.usa.gov#557]
## What kind of issue?
- [X] Feature Request?
- [ ] Bug

## User story
*Please provide us with a description of the issue as a user story*
The data on how many people are using the various government websites is neat, but it would be helpful in my line of work as a PTAC counselor if if provided a status on the websites (up or down), and if down, estimated time to get it back up again. I was helping a small business federal contractor update her entity registration in SAM a short while ago and SAM.gov apparently went down in the middle of our update. It would be nice to know that someone is aware of the issue and working on it, and when we might be able to come back and resume our work.

## Acceptance Criteria
- [ ]

**Comment by tdlowden** [comment]
Hi @philadopolis. This is an interesting suggestion, but alas, I think it's out of our realm of capability. Each individual site that participates in the program is managed by its own agency and team. We have no way to use Google Analytics to detect uptime, nor especially estimated time for recovery. Apologies, but this isn't something in our ability to do.
