### ISSUE TITLE
redirect to new api docs

### ISSUE THREAD

**Issue by gbinal** [18F/analytics.usa.gov#558]
## What kind of issue?
- [x] Feature Request?
- [ ] Bug

## User story
As a third party developer, I would like to be directed to the intended API docs and for there to not be duplicative API docs, so that I can easily start using the API.  

## Acceptance Criteria
- [ ] Change the api link in the footer to [the docs on open.gsa.gov](https://open.gsa.gov/api/dap/) and ensure that it opens in a new tab
- [ ] Add an API link in the top right of the site
- [ ] Change /developer and /developers to redirect to the new link

**Comment by tdlowden** [comment]
addressed with #560
