### ISSUE TITLE
access request for user; cryptofilegsa

### ISSUE THREAD

**Issue by cryptofilegsa** [18F/analytics.usa.gov#575]
## access request for: cryptofilegsa

- [ ]  https://github.com/18F/analytics.usa.gov
- [ ]  https://github.com/18F/analytics-reporter
- [ ]  https://github.com/18F/analytics-reporter-api
- [ ]  https://github.com/18F/analytics-restarter

## Purpose:
*Getting started with SSP and ATO documentation and potentially future contributions to source*

**Comment by tdlowden** [comment]
Thanks @cryptofilegsa! Since you have been assigned as a dev to assist with the upcoming ATO work, I will grant you access to the team that has permissions to these repos. In addition, I will add you as a user to the cloud.gov account.
