### ISSUE TITLE
Keyword or topic data

### ISSUE THREAD

**Issue by jessicaorquina** [18F/analytics.usa.gov#598]
## What kind of issue?
- [x] Feature Request?

I'd like to see a report that shows either keyword searches or includes topic/keyword data of webpages visited. For example, being able to search that 10% of government web traffic in the past 30 days was to webpages related to education or health, etc.

**Comment by tdlowden** [comment]
Hi @jessicaorquina. Sorry for the delayed response! We actually tried to take this on a couple years ago, but it was very difficult to get consensus on which domains belonged in which categories. Some are very broad. Hopefully, someday we can implement something like you suggest, but as of now, it isn't possible. Apologies.
