### ISSUE TITLE
http://nhlbi.nih.gov/ links are broken

### ISSUE THREAD

**Issue by abitrolly** [18F/analytics.usa.gov#612]
## What kind of issue?
- [x] Bug

## User story
As a visitor, I would like to follow the links on the right for Department of Health and Human Services, so that I can actually check Top Pages and Top Downloads by myself.

However the links are rendered without `www.` prefix and http://nhlbi.nih.gov/ just doesn't work without it.

## Acceptance Criteria
- [ ] add redirect to `www.` to http://nhlbi.nih.gov/ web server configuration

**Comment by tdlowden** [comment]
Hi @abitrolly, thanks for this. Unfortunately, that would be on NIH to enforce a www. redirect. We strip www. out in our systems to avoid disaggregation of www.- and non-www.- URLs that direct to the same place. I understand your frustration, but we can't implement that redirect on our end. Apologies.

**Comment by abitrolly** [comment]
@tdlowden I thought that it is `18F` role to explain those at NIH how to get this right. I don't see any other way for a citizen to affect them.

**Comment by tdlowden** [comment]
Apologies. I suggest you reach out to NIH.

**Comment by abitrolly** [comment]
@tdlowden so how does `18F` works then?
