### ISSUE TITLE
Include estimated numbers of authenticated users in reporting

### ISSUE THREAD

**Issue by ethanheppner** [18F/analytics.usa.gov#622]
## What kind of issue?
- [x] Feature Request

## User story
As a member of the login.gov partnerships team, or a potential customer of login.gov, I would like to see the number of authenticated visits to agency websites if possible, so that I can accurately estimate the user volume before signing an IAA for login/gov services.

(This feature would be handy for the login.gov team as well-- getting a better sense of what some of the biggest potential markets for our services are. We currently use analytics.usa.gov data to compare the number of login.gov authenticated users against overall number of unique visitors [here](https://docs.google.com/spreadsheets/d/1YeXCwvyxqTZ2F_lq90vrJSIkKdCRe5WcAYaONGtIMuo/edit?ts=5e9481a9&pli=1#gid=659639010))

## Acceptance Criteria
-  Ability to pull the monthly report with estimated numbers of authenticated users per domain.

**Comment by tdlowden** [comment]
Hi @ethanheppner. DAP specifically should not be present on pages after an authentication. See our implementation repo for more: https://github.com/digital-analytics-program/gov-wide-code#appropriate-placement

Unfortunately, as a result, this is not an option for our reporting.

**Comment by ethanheppner** [comment]
Ah, OK, makes sense. Thanks for pointing me towards this.

Ethan Heppner
Program Analyst, TTS Business Operations
https://gsa.gov/tts

**Comment by tdlowden** [comment]
Sorry we couldn't be of more help!
