### ISSUE TITLE
Request write collaborator access for ryan.wold@gsa.gov (ryanwoldatwork) on analytics repos

### ISSUE THREAD

**Issue by ryanwoldatwork** [18F/analytics.usa.gov#644]
Request write access to the following repos in order to assist with maintenance tasks on dependency updates for ryan.wold@gsa.gov (https://github.com/ryanwoldatwork)

https://github.com/18F/analytics.usa.gov/
https://github.com/18F/analytics-reporter
https://github.com/18F/analytics-reporter-api

**Comment by tdlowden** [comment]
As system owner, I approve of this access.
