### ISSUE TITLE
ensure PR branches run CI

### ISSUE THREAD

**Issue by ryanwoldatwork** [18F/analytics.usa.gov#649]
# Context / Impetus

[This PR](https://github.com/18F/analytics.usa.gov/pull/647) passed the GitHub checks, but the checks only include Snyk, but not CircleCI. 
Thus, when merged to master, that branch failed in CircleCI.

# Story

As a Developer,
I want to ensure branches are run in CircleCI,
So that I have confidence changes are working and suitable to merge

# Acceptance Criteria

When PR is opened
Then the branch should run in CircleCI
And the results of the job should be displayed in GitHub "Checks" for a given PR branch.

**Comment by levinmr** [comment]
done
