### ISSUE TITLE
Data CSVs lagging in recency

### ISSUE THREAD

**Issue by tdlowden** [18F/analytics.usa.gov#713]
## What kind of issue?
- [ ] Feature Request?
- [X] Bug

## User story
*Please provide us with a description of the issue as a user story*
As a public visitor, I would like CSV data on analytics.usa.gov/data to be as recent as possible, so that I can analyze it.

## Acceptance Criteria
- [ ]  All data reflects the most recent time period

## Notes
Example:
https://analytics.usa.gov/data/live/browsers.csv and 
https://analytics.usa.gov/data/live/os-browsers.csv

appear to be updating, but are running ~15-45 days behind. The most recent date for either of the report datapoints is in Sept.

**Comment by ryanhofdotgov** [comment]
@tdlowden Looks like it might be [hitting up against a max query limit of 10,000](https://developers.google.com/analytics/devguides/reporting/core/v3/reference#:~:text=If%20max%2Dresults%20is%20not,dimension%20segments%20as%20you%20expect.).

**Comment by tdlowden** [comment]
Wow. That is some great sleuthing, @ryanhofdotgov! I just looked at the csv and it does indeed have 10K rows. In that case, maybe the fix is to impose higher floor threshold in order to make the list?

**Comment by tdlowden** [comment]
Something odd is going on. @ryanhofdotgov  look at the results here: https://analytics.usa.gov/data/live/browsers.json

it says `>100` sessions, but there are rows that have less. And, they are in a strange ordering once you get past the top 1/3 or so. They aren't listed in descending order.

**Comment by tdlowden** [comment]
This is something odd:

![image](https://user-images.githubusercontent.com/6556888/95897500-a8328400-0d5b-11eb-87bc-cc5d1e412af3.png)


883 entries in the csv with lyft:android:, and with odd numbers.

I hesitate to even investigate what this is.

**Comment by ryanhofdotgov** [comment]
I saw that comment too, but it is a lie :) Take a look at value for `filters` – it just says `> 10`.

**Comment by tdlowden** [comment]
Yeah, I just spotted that.

There is quirk with the way the JSON compiles vs the CSV. The CSV lists the results daily, and each must be over 10 to make any single day's rows. On Monday if there are 12, it makes the report. On Tuesday if there are 8, it's not there. The JSON just does a cumulative add up of all those days to give you the 90 day totals. But those 20 total visits with X browser only show up at 12, bc the 8 from Tuesday didn't make the cut. 

Regardless, maybe we should just up the daily threshold to 100 visits. Most of the <100 daily stuff is pretty spurious anyway. Thoughts?

**Comment by tdlowden** [comment]
Update:  With the PR from @echappen above, we raised the min threshold for reporting each day to 100, which over time will decrease total rows each day, but is not retroactive. As of now, the reports are 8 days behind, but should catch up soon. Moving to close.
