### ISSUE TITLE
NASA data downloads inconsistent

### ISSUE THREAD

**Issue by tdlowden** [18F/analytics.usa.gov#738]
## What kind of issue?
- [ ] Feature Request?
- [X] Bug

## User story
*Please provide us with a description of the issue as a user story*
As a public user, I would like to have consistent and complete data on NASA sites, so that I can compare over time.

## Notes

https://analytics.usa.gov/data/national-aeronautics-space-administration/all-domains-30-days.csv

is reporting inconsistently. some days it has ~700 domains, some days only ~300.

**Comment by levinmr** [comment]
Closing stale issue.  Please reopen if this is still a problem
