### ISSUE TITLE
Individual page views and link clicks

### ISSUE THREAD

**Issue by deoyani** [18F/analytics.usa.gov#741]
## What kind of issue?
- [ ] Feature Request?
Is there a way to get the page views and link clicks like in GA available for each individual links within website.
- [ ] Bug

## User story
*Please provide us with a description of the issue as a user story*
We have a publicly used web application developed in angular and we have set up DAP analytics set up for the same. 
However if I want to get individual file link click or page view, I do  not see any existing API endpoints which I can use to get the data. We would like to use the api to get analytics per page to be able to show metrics on the page.
I sent an email on the contact listed on the page below but I was just asked to submit the issue.
https://open.gsa.gov/api/dap/
This page does not give details about whether we have such page views queries.

## Acceptance Criteria
- [ ]

**Comment by tdlowden** [comment]
Hi!

Do you work for a federal agency or as a federal contractor? For data as granular as you are asking, access to the GA account is more suitable If you are a fed employee or contractor, email dap@support.digitalgov.gov and we can get you access.

**Comment by deoyani** [comment]
Thanks for the reply , yes I am working for Federal agency and do have GA account access. I will send an email to mentioned id.

**Comment by mgifford** [comment]
@tdlowden that email gave me:  
  
**Delivery Status Notification (Failure)**

This message could not be delivered due to a recipient error. Please try again later.  
  
  
  
Is [dap@support.digitalgov.gov](mailto:dap@support.digitalgov.gov) still valid?

**Comment by tdlowden** [comment]
No. you can use dap@gsa.gov now

**Comment by levinmr** [comment]
Closing stale issue.  Please reopen if this is still a problem
