### ISSUE TITLE
Increase time range options to 6 mo, 1 year

### ISSUE THREAD

**Issue by mchelen-gov** [18F/analytics.usa.gov#799]
## What kind of issue?
- [x] Feature Request?
- [ ] Bug

## User story
*Please provide us with a description of the issue as a user story*
As a member of the public,
I would like to see data for a longer period of time,
so that I can better understand historical trends.

## Acceptance Criteria
- [ ] Able to view longer time periods such as 6 months or 1 year

**Comment by tdlowden** [comment]
Hi! Have you seen our API? You can use custom date ranges there, and it goes back a few years:

https://open.gsa.gov/api/dap/

Let me know if this meets your needs!

**Comment by mchelen-gov** [comment]
@tdlowden Thanks for the quick response! Yup the API option is wonderful, thought it might be nice to have in the UI as well?

**Comment by tdlowden** [comment]
Noted. thanks for the feedback!

**Comment by firmai** [comment]
Hi any tips on how to use the date parameter in the API. I have glanced over the documentation and it doesn't immediately appear obvious. Perhaps I am looking at the wrong documentation?
