### ISSUE TITLE
502 Response Encountered

### ISSUE THREAD

**Issue by rasikaramanan** [18F/analytics.usa.gov#855]
## What kind of issue?
- [ ] Feature Request?
- [ ] Bug

## User story
*Please provide us with a description of the issue as a user story*
I received a 502 Bad Gateway response when attempting to GET data with the following link:
https://api.gsa.gov/analytics/dap/v1.1/domain/fda.gov/reports/site/data?api_key=DEMO_KEY1

## Acceptance Criteria
- [ ]

**Comment by tdlowden** [comment]
Thanks for this! We are aware of this issue and working to try to fix it. cc @ryanwoldatwork

**Comment by tdlowden** [comment]
Are you still encountering this error @rasikaramanan ?

**Comment by rasikaramanan** [comment]
@tdlowden no, it works now! Thanks
