### ISSUE TITLE
How specific can queries get?

### ISSUE THREAD

**Issue by jguch** [18F/analytics.usa.gov#860]
## What kind of issue?
- [x] Feature Request?
- [ ] Bug

## User story
*Please provide us with a description of the issue as a user story*
As a team lead managing a series of Census applications, I would like to obtain detailed statistics on our apps, so that I can provide valuable information to the subject matter experts.

## Acceptance Criteria
- [ ] 

## Notes
I have recently obtained an API key.  I see that I can obtain general information at the agency-level (i.e., Census Bureau) - for example, https://api.gsa.gov/analytics/dap/v1.1/domain/census.gov/reports/site/data?api_key=<API_KEY>, but when I try to combine endpoints to get a more specific result (e.g., which browsers are users using when visiting census.gov - https://api.gsa.gov/analytics/dap/v1.1/domain/census.gov/reports/browser/data?api_key=<API_KEY>), I get the following error message: "{"message":"You are requesting a report that cannot be filtered on domain. Please try one of the following reports: site, domain, download, second-level-domain.","status":400}" 

Is there a way I can drill down deeper to find more granular stats?

Thanks,

John

**Comment by tdlowden** [comment]
Hi John! So sorry this has been out here without reply. The best way for you to get the granular info you wish is to get access to the underlying DAP GA account. If you are an employee or contractor working for Census, you can request access by emailing dap@gsa.gov.
