### ISSUE TITLE
Hourly bar chart delayed by an hour?

### ISSUE THREAD

**Issue by leahbannon** [18F/analytics.usa.gov#87]
Screenshot taken at 9:30am

![uploads/072ceec1-3dc2-4ec5-b1cf-51463b3524f3/Screen Shot 2015-01-16 at 9.31.35 AM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F072ceec1-3dc2-4ec5-b1cf-51463b3524f3%2FScreen+Shot+2015-01-16+at+9.31.35+AM.png)

**Comment by ramirezg** [comment]
@leahbannon unfortunately this is GA quirk, the hourly reports are always behind. We could switch to a more granular minute report, but the data would loose a lot of accuracy. 

https://gist.github.com/ramirezg/d64ce37d8547cbcc0f2d

**Comment by ramirezg** [comment]
We could also remove the incomplete numbers to make it look better? Incomplete defined as : anything in the series that is less than 10% of the last number
something like 18F/analytics-reporter/pull/71

**Comment by konklone** [comment]
Yeah, I think the solution here is, if we know GA is delayed by 1.X hours, to intentionally show data only up to 2 hours ago, and then label the graph as 2 hours behind.

As @leahbannon pointed out, we will definitely need to _say_ it's 2 hours behind, since we also go out of our way to label the time zone as Eastern Time, and the data will look like it's from another timezone if it's missing 2 hours of data.

**Comment by ramirezg** [comment]
At first I thought this might have been a time zone issue, but I just check GA's time settings are correct. 
##### The report time zone appears to be in EST
![screen shot 2015-01-26 at 9 53 53 am](https://cloud.githubusercontent.com/assets/4596845/5901878/d4d7738e-a543-11e4-910e-5916f9724187.png)

In any case, I submitted a [PR 76](https://github.com/18F/analytics-reporter/pull/76) to show only data up to the last two hours. Still, we could also just warn users that the report sometimes lags 1-2 hours.

**Comment by gbinal** [comment]
We don't have plans to revisit the design anytime soon, so I'm going to close this issue for now.  It'll still have the `Backlog` label on it in case we want to revisit and open.
