### ISSUE TITLE
Visits to domains over past year?

### ISSUE THREAD

**Issue by zfasnacht** [18F/analytics.usa.gov#880]
## User story
As a scientist with NASA it would be very useful to be able to track the number of views on our pages over the past year in addition to over the past 30 days. I'm not sure how feasible this would be, but it would be very beneficial.

**Comment by tdlowden** [comment]
Hi. Some information is available for longer time periods in the API: https://open.gsa.gov/api/dap/, but additionally, if you are a NASA employee or contractor, you can request access to the much more robust and dynamic Google Analytics account that powers analytics.usa.gov: https://digital.gov/guides/dap/gaining-access-to-dap-data/

**Comment by richiboi1977** [comment]
I'm not the only one on the account sir I gotten compromised over 4 years ago besides I never seen any document or equipment at all till I found the identity theft happening to be I just opened a developers program to contact you in some way through fbi 3 years ago that a man from china was wanting me to give him a business proposition he wanted me to be his custodial manager for a very large some of money I reported thinking it was a scam not only that the whole Spanish population is fixing to start a revolution somewhere between I think hollowed they also got into the account I was wondering how a old cook was getting free coverage on my phone all the time I never received any benefits my irs,credit, subs,ppp, forgiveness including supposed partnerships never happened you got scammed to by the developer who created the fake apps and Google store I already had on here before I opened this iPhone I bought up in the art store with 3rd part software I'm curious why I gotten it or why I am involved till I started taking snap shots of the documents I had to erase before the Russian developer almost took all the documents if I didn't and taker screen shots instead
