### ISSUE TITLE
(Bug) API Calls to /domain/*/reports/site/data are hanging

### ISSUE THREAD

**Issue by ppsweb** [18F/analytics.usa.gov#883]
I'm using postman to call this URL:
  https://api.gsa.gov/analytics/dap/v1.1/domain/usajobs.gov/reports/site/data?api_key=MY_API_KEY

I'm fairly sure this exact endpoint was working a few weeks ago but now its just hanging. It's not failing, so theres no error message to report, but it just hangs in Postman with no response. 

Other endpoints are working just fine for me, so its not my API Key. 

Any idea why this is failing all of a sudden?

**Comment by ppsweb** [comment]
Hey @tdlowden just checking in - any idea what happened to this endpoint?

**Comment by tdlowden** [comment]
Hi ppsweb. We tried to figure this out a few months ago, as referenced at https://github.com/18F/analytics-reporter-api/issues/122. Honestly, we thought we solved it. But apparently it is still occurring. If I'm being honest, we don't have resources at the moment to try to dig really deep into the API. I will mark it in our roadmap for investigation, but I can't commit to any timeline for a fix. apologies

**Comment by ppsweb** [comment]
Ok gotcha, thanks for your quick response - I'll follow that other issue to keep track of it. Thanks all of your work on this project! You can close this issue as a duplicate if you want.

**Comment by Souvik-Root** [comment]
Hi,

Any updates on this issue?

I tried the API Url - https://api.gsa.gov/analytics/dap/v1.1/domain/weather.gov/reports/domain/data?api_key=MY_API_KEY

It does not return any response and just keeps loading. Then I get 504 Connection Time Out.

**Comment by tdlowden** [comment]
Hi. No updates as of now. My recommendation would be to try using the `limit` parameter to decrease the amount of records or run the report without specifying `domain` and extract the weather.gov information from the larger list. Sorry, we haven't been able to solve this!

**Comment by Souvik-Root** [comment]
@tdlowden 

I tried using the limit parameter making the url - https://api.gsa.gov/analytics/dap/v1.1/domain/weather.gov/reports/domain/data?limit=5

I tried this on postman and it took 39.92s to provide me with a response. 

![image](https://user-images.githubusercontent.com/97417844/156040238-9fb428b0-1a93-4981-88a4-845fedfde327.png)

**Comment by levinmr** [comment]
closing stale issue.  There are related items open on the https://github.com/18F/analytics-reporter-api repo
