### ISSUE TITLE
How can I download Software Licensing data from the DoNCIO? I am looking for data specific to Navy PEO MLB. What software are they using, company, cost, award, contract vehicles and Period of Performance.

### ISSUE THREAD

**Issue by SARATOGAMarine** [18F/analytics.usa.gov#884]
## What kind of issue?
- [ ] Feature Request?
- [ ] Bug

## User story
*Please provide us with a description of the issue as a user story*
As a <x kind of end user>, I would like to <y thing on the side>, so that I can <z provide the value of the change to the user>.

## Acceptance Criteria
- [ ]

**Comment by tdlowden** [comment]
Hi. This type of data is not available with our system. Sorry. Moving to close.
