### ISSUE TITLE
New feature: add regulations.gov to service

### ISSUE THREAD

**Issue by jweisman11** [18F/analytics.usa.gov#888]
## What kind of issue?
- [X] Feature Request?
- [ ] Bug

## User story
*Please provide us with a description of the issue as a user story*
As a citizen-data scientist, I would like to understand who is viewing and commenting on proposed regulations, so that I can identity patterns and potential bias.

## Acceptance Criteria
- [ ] Incorporate data from visits to regulations.gov into analytics.usa.gov
- [ ] In the "Top Pages" feature, identity the specific regulations (if it qualifies by page count)
- [ ] In the "Top Downloads" feature, identify specific files that been downloaded (if it qualifies by download count) -- for example, you can download regulations like this one (https://www.regulations.gov/document/DHS-2021-0051-0001) by clicking the button at the bottom of the page. 

## Notes
Incorporating site visit and download data from regulations.gov will enable decision makes and the public to better understand which regulations the citizenry, and more broadly the public, have a particular interest in. Beyond a simple "count of comments" available directly on regulations.gov, this data is not available anywhere else and would IMHO be a novel addition to analytics.usa.gov

**Comment by tdlowden** [comment]
Hi! Regulations.gov participates in DAP and is included in the analytics.usa.gov dataset. We don't create pages for specific websites, so you can get the information via the downloadable files options or the API.
