### ISSUE TITLE
Add State of Delaware to README

### ISSUE THREAD

**Issue by pathennessy** [18F/analytics.usa.gov#890]
## What kind of issue?
- [X] Feature Request?
- [ ] Bug

## User story
State of Delaware analytics site is missing from README.md.  I've submitted a pull request #889 to update the README.

## Acceptance Criteria
- [ ]

**Comment by tdlowden** [comment]
Done! and great work. Love to see it. 

https://twitter.com/tdlowden/status/1488578210883325954?s=20&t=6oOBt2NQpuJ1Zgsn8oiFzA
