### ISSUE TITLE
openapi.yaml file incorrectly specifies type for `before` and `after` parameters

### ISSUE THREAD

**Issue by jonquandt** [18F/analytics.usa.gov#896]
## What kind of issue?
- [ ] Feature Request?
- [X] Bug

## User story
*Please provide us with a description of the issue as a user story*
As a analytics API user, I would like to be able to use the openapi.yml file in postman, so that I can do more detailed analysis of analytics.usa.gov data.

## Acceptance Criteria
- [ ]  `before` and `after` parameters should be specified as type: string, format:date -- currently they are type:integer, which causes failures when trying to follow the YYYY-MM-DD format specified in the parameter description

## Notes
- I arrived at this issue tracker via https://open.gsa.gov/api/dap/, but I don't see the [openapi.yaml file](https://open.gsa.gov/api/dap/v1/openapi.yaml) referenced [here](https://open.gsa.gov/api/dap/#openapi-specification-file) within this repo, so sorry if putting in the wrong spot. 
- it looks like the yaml may be generated from annotations within the code

**Comment by levinmr** [comment]
done
