### ISSUE TITLE
ERR_CERT_AUTHORITY_INVALID

### ISSUE THREAD

**Issue by fkildoo** [18F/analytics.usa.gov#911]
## What kind of issue?

- [ ] Feature Request?
- [X] Bug

## User story
  
I manage a federal website and have had the DAP code implemented and working for quite a while now. However, when inspecting a page on my website with Chrome dev tools, I receive an error in the console regarding the certificate associated with https://dap.digitalgov.gov. 

Failed to load resource: net::ERR_CERT_AUTHORITY_INVALID

When visiting https://dap.digitalgov.gov directly, the address bar also shows the certificate is invalid:

![Screenshot 2023-02-22 163750](https://user-images.githubusercontent.com/12836525/220765104-34c09bea-2f15-4f16-8208-10dfdf3ad10f.png)

**Comment by ryanwoldatwork** [comment]
Hi @fkildoo - there is no site hosted at https://dap.digitalgov.gov directly,
rather, the domain is used to host the DAP script.

I hope this helps. Please let me know if you have any other questions, or if this is impacting you in a specific way.
