### ISSUE TITLE
"Realtime data may not be accurate"

### ISSUE THREAD

**Issue by MatthewJMcAllister** [18F/analytics.usa.gov#915]
Hi, it seems like everytime I've come to the site sporadically over the last three months I've seen the warning message at the top that says, "Realtime data may not be accurate". The numbers seem pretty dramatically off compared to the historical averages I recall seeing. Will this be updated? Is the platform continuing to receive support?

I lead a state-level digital service team and really want to be able to point to this website as an example of opening data and making decisions based on how the public interacts with public sector sites. This website feels like the gold standard - so long as it continues to be supported and have up-to-date data.

**Comment by Julianabrwon** [comment]
Inbox me directly

**Comment by smarina04** [comment]
@MatthewJMcAllister we are working on it as part of the analytics.usa.gov relaunch and migration to GA4, and will bring it back up as soon as possible.
