### ISSUE TITLE
Page while loading (or without data) looks like this

### ISSUE THREAD

**Issue by konklone** [18F/analytics.usa.gov#92]
It's not terrible, but could probably be planned a bit better:

![page without data](https://cloud.githubusercontent.com/assets/4592/5784701/afee7350-9d9c-11e4-8593-d5ac96833b6a.png)

**Comment by gbinal** [comment]
We don't have plans to revisit the design anytime soon, so I'm going to close this issue for now.  It'll still have the `Backlog` label on it in case we want to revisit and open.
