### ISSUE TITLE
OPM slug is incorrect

### ISSUE THREAD

**Issue by IHIutch** [18F/analytics.usa.gov#931]
## What kind of issue?
- [ ] Feature Request?
- [x] Bug

https://github.com/18F/analytics.usa.gov/blob/master/_data/agencies.json#L86-L88

**Comment by smarina04** [comment]
@XavierMetichecchia this will need to be fixed once the site is back up.

**Comment by IHIutch** [comment]
Just following up as it appears the latest PR to fix this may still be incorrect: https://github.com/18F/analytics.usa.gov/commit/28e3fd1a013fcb32e6c26b8dd00ffcb837a6d8d5#diff-d1ad2e04cc7291ab1ba54de9a4541f24592a83680d1253d873f5758990d41fd2R87

**Comment by IHIutch** [comment]
Fixed with  https://github.com/18F/analytics.usa.gov/pull/932
