### ISSUE TITLE
Favicon!

### ISSUE THREAD

**Issue by cew821** [18F/analytics.usa.gov#99]
Anyone have an idea?

**Comment by gbinal** [comment]
Here's the [USA.gov favicon](http://www.usa.gov/resources/images/usa_favicon.ico).

**Comment by konklone** [comment]
Ambitious idea: a number, which ticks up odometer-style, every X seconds. It doesn't have to take as much work as [Defender of the FAVICON](http://www.p01.org/releases/DEFENDER_of_the_favicon/), but it would be fun.

**Comment by kyledreger** [comment]
Hello, all &mdash; great job on the site! I love the direction USDS and 18F are taking government data, keep it up :+1: 

@konklone's comment about a dynamic icon got me thinking, and I thought it would be cool if the favicon updated with a mini-graph of the current day's traffic. Here's two variations on that idea: 

![analytics usa gov](https://cloud.githubusercontent.com/assets/1388077/6736736/0b85260c-ce3d-11e4-857b-d5dbcb67ed1a.png)

You could tie the favicon creation into your existing [crontab job](https://github.com/18F/analytics-reporter/blob/master/deploy/crontab), and then have your client-side JavaScript update the `<link href="">` attribute whenever it polls for data.

**Comment by athyuttamre** [comment]
You can use [favico.js](http://lab.ejci.net/favico.js/) to make dynamic favicons.

**Comment by tdlowden** [comment]
+1 +1 hoping to revisit this

**Comment by JuliaWinn** [comment]
<img width="753" alt="screen shot 2015-10-27 at 1 46 39 pm" src="https://cloud.githubusercontent.com/assets/821557/10767153/3246c962-7cb1-11e5-865d-f599335752dc.png">
We now have a basic favicon that is live on [staging](https://pages.18f.gov/analytics.usa.gov/).
